const { createClient } = require('@supabase/supabase-js')

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

const EXERCISES = [

// ═══════════════════════════════════════════════════════
// CHEST / KLATKA
// ═══════════════════════════════════════════════════════

// Horizontal Push
{ id:'barbell_bench_press', name_en:'Barbell Bench Press', name_pl:'Wyciskanie sztangi leżąc', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest'], secondary_muscles:['triceps','front_delts'], movement_pattern:'horizontal_push', exercise_type:'compound', equipment:['barbell'], tier:'A', role:'main', difficulty:'intermediate', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:4, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'4-10', recommended_rir:'1-3', rest_time_seconds:180, description_short:'Klasyczne ćwiczenie na klatkę z dużym potencjałem siłowym.', tier_reason:'Silny bodziec, ale gorszy stretch niż warianty DB/cable.', tags:['hypertrophy','strength','barbell','compound','chest'], sfr_rating:4, beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'medium' },

{ id:'dumbbell_bench_press', name_en:'Dumbbell Bench Press', name_pl:'Wyciskanie hantli leżąc', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest'], secondary_muscles:['triceps','front_delts'], movement_pattern:'horizontal_push', exercise_type:'compound', equipment:['dumbbell'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:3, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:150, description_short:'Większy zakres ruchu niż sztanga, lepszy stretch klatki.', tier_reason:'Lepsza pozycja rozciągnięcia niż barbell, bezpieczniejszy dla barku.', tags:['hypertrophy','dumbbell','compound','chest','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'machine_chest_press', name_en:'Machine Chest Press', name_pl:'Wyciskanie na maszynie poziomej', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest'], secondary_muscles:['triceps','front_delts'], movement_pattern:'horizontal_push', exercise_type:'compound', equipment:['machine'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-20', recommended_rir:'0-3', rest_time_seconds:120, description_short:'Stabilne wyciskanie na maszynie — idealne dla początkujących i pump setów.', tier_reason:'Dobry bodziec, stałe napięcie, bezpieczny dla barku.', tags:['hypertrophy','machine','stable','chest','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'push_up', name_en:'Push-up', name_pl:'Pompki', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest'], secondary_muscles:['triceps','front_delts','core'], movement_pattern:'horizontal_push', exercise_type:'compound', equipment:['bodyweight'], tier:'B', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:3, fatigue_rating:2, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'10-30', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Klasyczne ćwiczenie bez sprzętu. Dobre jako uzupełnienie lub warm-up.', tier_reason:'Ograniczona progresja bez obciążenia, ale użyteczne.', tags:['bodyweight','chest','beginner_friendly','no_equipment'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

// Incline Push
{ id:'incline_barbell_press', name_en:'Incline Barbell Press', name_pl:'Wyciskanie sztangi na ławce skośnej', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest_upper','front_delts'], secondary_muscles:['triceps'], movement_pattern:'incline_push', exercise_type:'compound', equipment:['barbell'], tier:'B', role:'main', difficulty:'intermediate', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:4, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'6-12', recommended_rir:'1-3', rest_time_seconds:180, description_short:'Akcentuje górną część klatki i przednie deltoid.', tier_reason:'Dobry na górną klatkę, ale duże zaangażowanie barków i słabszy stretch.', tags:['hypertrophy','barbell','chest_upper','incline'], beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'medium' },

{ id:'incline_dumbbell_press', name_en:'Incline Dumbbell Press', name_pl:'Wyciskanie hantli na ławce skośnej', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest_upper'], secondary_muscles:['triceps','front_delts'], movement_pattern:'incline_push', exercise_type:'compound', equipment:['dumbbell'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:3, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:150, description_short:'Jeden z najlepszych wyborów na górną część klatki ze stretch position.', tier_reason:'Lepsza pozycja rozciągnięcia niż barbell incline, bezpieczniejszy.', tags:['hypertrophy','dumbbell','chest_upper','incline','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'chest_dips', name_en:'Chest Dips', name_pl:'Dipy na klatkę piersiową', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest_lower'], secondary_muscles:['triceps','front_delts'], movement_pattern:'incline_push', exercise_type:'compound', equipment:['bodyweight'], tier:'B', role:'secondary', difficulty:'intermediate', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:3, sfr_rating:3, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Dipy z tułowiem pochylonym do przodu — akcentuje dolną część klatki.', tier_reason:'Dobry stretch, ale ryzyko barku przy złej technice.', tags:['hypertrophy','bodyweight','chest_lower','compound'], beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'medium' },

// Fly / Adduction
{ id:'cable_fly', name_en:'Cable Fly', name_pl:'Rozpiętki na wyciągu', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest'], secondary_muscles:[], movement_pattern:'fly_adduction', exercise_type:'isolation', equipment:['cable'], tier:'S', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:5, fatigue_rating:2, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Najlepsze ćwiczenie izolowane na klatkę — stałe napięcie i stretch przez cały zakres.', tier_reason:'Najwyższy SFR dla klatki — stretch position + stałe napięcie cable.', tags:['hypertrophy','cable','isolation','chest','lengthened_bias','high_stimulus','low_fatigue'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'low_to_high_cable_fly', name_en:'Low-to-High Cable Fly', name_pl:'Rozpiętki na wyciągu dolnym', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest_upper'], secondary_muscles:['front_delts'], movement_pattern:'fly_adduction', exercise_type:'isolation', equipment:['cable'], tier:'S', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:5, fatigue_rating:2, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Akcentuje górną klatkę, świetne uzupełnienie do incline press.', tier_reason:'Stałe napięcie, stretch górnej klatki — wyjątkowy SFR.', tags:['hypertrophy','cable','isolation','chest_upper','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'pec_deck', name_en:'Pec Deck', name_pl:'Rozpiętki na maszynie (Pec Deck)', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest'], secondary_muscles:[], movement_pattern:'fly_adduction', exercise_type:'isolation', equipment:['machine'], tier:'A', role:'accessory', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Stabilna maszyna do izolacji klatki, dobra dla początkujących.', tier_reason:'Dobry bodziec, stabilna — ale stałe napięcie słabsze niż cable.', tags:['hypertrophy','machine','isolation','chest','stable','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'single_arm_cable_fly', name_en:'Single-Arm Cable Fly', name_pl:'Rozpiętki na wyciągu jedną ręką', body_region:'upper_body', muscle_group:'chest', primary_muscles:['chest'], secondary_muscles:[], movement_pattern:'fly_adduction', exercise_type:'isolation', equipment:['cable'], tier:'A', role:'pump', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-2', rest_time_seconds:75, description_short:'Unilateralna wersja — dobra do korekcji dysproporcji.', tier_reason:'Stretch i napięcie jak cable fly, plus korekcja stron.', tags:['hypertrophy','cable','isolation','chest','unilateral'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low', unilateral:true },

// ═══════════════════════════════════════════════════════
// BACK / PLECY
// ═══════════════════════════════════════════════════════

{ id:'pull_up', name_en:'Pull-up', name_pl:'Podciąganie na drążku', body_region:'upper_body', muscle_group:'back', primary_muscles:['lats','biceps'], secondary_muscles:['rear_delts','rhomboids'], movement_pattern:'vertical_pull', exercise_type:'compound', equipment:['bodyweight'], tier:'A', role:'main', difficulty:'intermediate', skill_requirement:3, stability_requirement:3, stimulus_rating:5, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'5-15', recommended_rir:'1-3', rest_time_seconds:150, description_short:'Jedno z najlepszych ćwiczeń na szerokie plecy i biceps.', tier_reason:'Wysoki bodziec, świetny stretch — ale trudne dla początkujących i ograniczona progresja.', tags:['hypertrophy','strength','bodyweight','compound','lats','vertical_pull'], beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'lat_pulldown', name_en:'Lat Pulldown', name_pl:'Ściąganie drążka wyciągu górnego', body_region:'upper_body', muscle_group:'back', primary_muscles:['lats'], secondary_muscles:['biceps','rear_delts'], movement_pattern:'vertical_pull', exercise_type:'compound', equipment:['cable','lat_pulldown'], tier:'S', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:1, stimulus_rating:5, fatigue_rating:3, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Najlepsze ćwiczenie na szerokie plecy dla większości klientów.', tier_reason:'Stałe napięcie cable, stretch latissimus, łatwa progresja — S tier.', tags:['hypertrophy','cable','compound','lats','vertical_pull','beginner_friendly','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'single_arm_lat_pulldown', name_en:'Single-Arm Lat Pulldown', name_pl:'Ściąganie wyciągu górnego jedną ręką', body_region:'upper_body', muscle_group:'back', primary_muscles:['lats'], secondary_muscles:['biceps'], movement_pattern:'vertical_pull', exercise_type:'compound', equipment:['cable'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'10-15', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Unilateralna wersja lat pulldown — świetna korekcja dysproporcji.', tier_reason:'Lepsza izolacja i korekcja stron niż oburącz.', tags:['hypertrophy','cable','lats','unilateral','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low', unilateral:true },

{ id:'straight_arm_pulldown', name_en:'Straight-Arm Cable Pulldown', name_pl:'Ściąganie ramion prostych na wyciągu', body_region:'upper_body', muscle_group:'back', primary_muscles:['lats'], secondary_muscles:['teres_major','chest'], movement_pattern:'lat_isolation', exercise_type:'isolation', equipment:['cable'], tier:'A', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Izolacja latissimus — izoluje plecy od bicepsa.', tier_reason:'Świetny stretch lat bez obciążenia bicepsa — unikalne.', tags:['hypertrophy','cable','isolation','lats','lengthened_bias','lat_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'barbell_row', name_en:'Barbell Row', name_pl:'Wiosłowanie sztangą', body_region:'upper_body', muscle_group:'back', primary_muscles:['lats','rhomboids','traps'], secondary_muscles:['biceps','rear_delts','erectors'], movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['barbell'], tier:'B', role:'main', difficulty:'intermediate', skill_requirement:4, stability_requirement:4, stimulus_rating:5, fatigue_rating:5, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'5-10', recommended_rir:'1-3', rest_time_seconds:180, description_short:'Ciężkie wiosłowanie — silny bodziec ale duże zmęczenie ogólnoustrojowe.', tier_reason:'Wysoki bodziec, ale wysokie zmęczenie i ryzyko lędźwi — niski SFR.', tags:['strength','barbell','compound','back','high_fatigue','lower_back_risk'], beginner_friendly:false, lower_back_fatigue:'high', joint_risk:'medium' },

{ id:'chest_supported_row', name_en:'Chest Supported Row', name_pl:'Wiosłowanie podparte o ławkę', body_region:'upper_body', muscle_group:'back', primary_muscles:['rhomboids','traps','rear_delts'], secondary_muscles:['biceps','lats'], movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['dumbbell'], tier:'S', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:1, stimulus_rating:5, fatigue_rating:3, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Wiosłowanie bez obciążenia lędźwi — najlepszy SFR dla pleców.', tier_reason:'Eliminuje compensation lędźwi — czyste napięcie pleców, S tier.', tags:['hypertrophy','dumbbell','compound','back','stable','lengthened_bias','high_stimulus'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'cable_row', name_en:'Seated Cable Row', name_pl:'Wiosłowanie wyciągiem siedząc', body_region:'upper_body', muscle_group:'back', primary_muscles:['rhomboids','lats','traps'], secondary_muscles:['biceps','rear_delts'], movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['cable'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Stałe napięcie cable — świetne wiosłowanie poziome z pełnym stretchem.', tier_reason:'Stałe napięcie przez cały zakres, lepsza kontrola niż barbell.', tags:['hypertrophy','cable','compound','back','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'dumbbell_row', name_en:'Dumbbell Row', name_pl:'Wiosłowanie hantlem', body_region:'upper_body', muscle_group:'back', primary_muscles:['lats','rhomboids'], secondary_muscles:['biceps','rear_delts'], movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['dumbbell'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Jednostronne wiosłowanie — lepsza izolacja niż barbell, stretch latissimus.', tier_reason:'Dobry stretch i unilateral kontrola — praktyczne i efektywne.', tags:['hypertrophy','dumbbell','compound','back','unilateral','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low', unilateral:true },

{ id:'single_arm_cable_row', name_en:'Single-Arm Cable Row', name_pl:'Wiosłowanie wyciągiem jedną ręką', body_region:'upper_body', muscle_group:'back', primary_muscles:['lats','rhomboids'], secondary_muscles:['biceps'], movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['cable'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'10-15', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Unilateralne wiosłowanie na wyciągu — korekcja dysproporcji i lepszy zakres.', tier_reason:'Pełen zakres ruchu z rotacją tułowia, stałe napięcie.', tags:['hypertrophy','cable','back','unilateral','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low', unilateral:true },

{ id:'face_pull', name_en:'Face Pull', name_pl:'Przyciąganie linki do twarzy', body_region:'upper_body', muscle_group:'back', primary_muscles:['rear_delts','upper_traps','rhomboids'], secondary_muscles:['external_rotators'], movement_pattern:'scapular_retraction', exercise_type:'isolation', equipment:['cable'], tier:'A', role:'prehab', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:1, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'15-25', recommended_rir:'1-3', rest_time_seconds:75, description_short:'Kluczowe dla zdrowia barku i górnych pleców — obowiązek każdego planu.', tier_reason:'Prehab i hipertrofia tylnego deltoidu w jednym.', tags:['prehab','cable','rear_delts','upper_back_bias','joint_friendly','shoulder_health'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'deadlift', name_en:'Deadlift', name_pl:'Martwy ciąg klasyczny', body_region:'lower_body', muscle_group:'back', primary_muscles:['erectors','glutes','hamstrings'], secondary_muscles:['lats','traps','quads'], movement_pattern:'hip_hinge', exercise_type:'compound', equipment:['barbell'], tier:'B', role:'main', difficulty:'advanced', skill_requirement:5, stability_requirement:5, stimulus_rating:5, fatigue_rating:5, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'3-6', recommended_rir:'2-3', rest_time_seconds:240, description_short:'Król ćwiczeń siłowych — ale niski SFR dla hipertrofii.', tier_reason:'Świetny na siłę, ale wysoka cena zmęczenia i ryzyko lędźwi — nie najlepszy dla hipertrofii.', tags:['strength','barbell','compound','high_fatigue','lower_back_risk','advanced'], beginner_friendly:false, lower_back_fatigue:'high', joint_risk:'high' },

// ═══════════════════════════════════════════════════════
// SHOULDERS / BARKI
// ═══════════════════════════════════════════════════════

{ id:'dumbbell_shoulder_press', name_en:'Dumbbell Shoulder Press', name_pl:'Wyciskanie hantli nad głowę', body_region:'upper_body', muscle_group:'shoulders_lat', primary_muscles:['front_delts','lateral_delts'], secondary_muscles:['triceps','upper_traps'], movement_pattern:'vertical_push', exercise_type:'compound', equipment:['dumbbell'], tier:'A', role:'main', difficulty:'intermediate', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:150, description_short:'Klasyczne wyciskanie nad głowę z hantlami — dobry bodziec frontalnych.', tier_reason:'Dobre ćwiczenie ogólne na barki — ale słaby stretch bocznych.', tags:['hypertrophy','dumbbell','compound','shoulders','vertical_push'], beginner_friendly:false, lower_back_fatigue:'medium', joint_risk:'medium' },

{ id:'machine_shoulder_press', name_en:'Machine Shoulder Press', name_pl:'Wyciskanie na maszynie nad głowę', body_region:'upper_body', muscle_group:'shoulders_lat', primary_muscles:['front_delts','lateral_delts'], secondary_muscles:['triceps'], movement_pattern:'vertical_push', exercise_type:'compound', equipment:['machine'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Stabilna maszyna — dobra dla początkujących i bezpieczna dla barku.', tier_reason:'Dobry bodziec z minimalnym ryzykiem — idealny na wysokie serie.', tags:['hypertrophy','machine','compound','shoulders','stable','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'cable_lateral_raise', name_en:'Cable Lateral Raise', name_pl:'Unoszenie ramienia bokiem na wyciągu', body_region:'upper_body', muscle_group:'shoulders_lat', primary_muscles:['lateral_delts'], secondary_muscles:['upper_traps','supraspinatus'], movement_pattern:'shoulder_abduction', exercise_type:'isolation', equipment:['cable'], tier:'S', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:5, fatigue_rating:2, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-25', recommended_rir:'0-3', rest_time_seconds:75, setup:'Ustaw wyciąg nisko. Stań bokiem do wyciągu i złap uchwyt dalszą ręką.', execution:'Unoś ramię bokiem kontrolowanie, prowadząc ruch łokciem. Nie unoś barku do ucha.', cues:['Łokieć prowadzi ruch','Bark daleko od ucha','Nie zarzucaj tułowiem','Kontroluj dolną fazę'], common_mistakes:['Zarzucanie ciężarem','Praca kapturami','Za duży ciężar','Brak kontroli w dole'], description_short:'Najlepsze ćwiczenie izolowane na boczny akton barków.', tier_reason:'Świetny bodziec, niski koszt zmęczenia i bardzo dobra kontrola napięcia.', tags:['hypertrophy','cable','isolation','lateral_delts','lengthened_bias','low_fatigue','high_stimulus'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'dumbbell_lateral_raise', name_en:'Dumbbell Lateral Raise', name_pl:'Unoszenie ramion bokiem z hantlami', body_region:'upper_body', muscle_group:'shoulders_lat', primary_muscles:['lateral_delts'], secondary_muscles:['upper_traps'], movement_pattern:'shoulder_abduction', exercise_type:'isolation', equipment:['dumbbell'], tier:'B', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:3, fatigue_rating:2, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:75, description_short:'Klasyczne unoszenie hantli — dobre, ale gorsze napięcie niż cable.', tier_reason:'Dobre ćwiczenie, ale brak napięcia w dolnej fazie ruchu.', tags:['hypertrophy','dumbbell','isolation','lateral_delts'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'machine_lateral_raise', name_en:'Machine Lateral Raise', name_pl:'Unoszenie ramion bokiem na maszynie', body_region:'upper_body', muscle_group:'shoulders_lat', primary_muscles:['lateral_delts'], secondary_muscles:[], movement_pattern:'shoulder_abduction', exercise_type:'isolation', equipment:['machine'], tier:'A', role:'accessory', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:75, description_short:'Stabilna maszyna z dobrym napięciem przez cały zakres.', tier_reason:'Stałe napięcie i stretch — lepsza niż hantle, prawie jak cable.', tags:['hypertrophy','machine','isolation','lateral_delts','stable','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'reverse_pec_deck', name_en:'Reverse Pec Deck', name_pl:'Odwrotne rozpiętki na maszynie (tylny deltoid)', body_region:'upper_body', muscle_group:'shoulders_rear', primary_muscles:['rear_delts'], secondary_muscles:['rhomboids','upper_traps'], movement_pattern:'shoulder_extension', exercise_type:'isolation', equipment:['machine'], tier:'S', role:'accessory', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:5, fatigue_rating:2, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-25', recommended_rir:'0-3', rest_time_seconds:75, description_short:'Najlepsze izolowane ćwiczenie na tylny deltoid.', tier_reason:'Stałe napięcie, pełny stretch tylnego deltoidu — S tier dla partii.', tags:['hypertrophy','machine','isolation','rear_delts','lengthened_bias','stable','low_fatigue'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'rear_delt_cable_fly', name_en:'Rear Delt Cable Fly', name_pl:'Rozpiętki na wyciągu na tylny deltoid', body_region:'upper_body', muscle_group:'shoulders_rear', primary_muscles:['rear_delts'], secondary_muscles:['rhomboids'], movement_pattern:'shoulder_extension', exercise_type:'isolation', equipment:['cable'], tier:'A', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:75, description_short:'Efektywna izolacja tylnego deltoidu na wyciągu.', tier_reason:'Dobry stretch i napięcie, elastyczna pozycja ciała.', tags:['hypertrophy','cable','isolation','rear_delts','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

// ═══════════════════════════════════════════════════════
// BICEPS
// ═══════════════════════════════════════════════════════

{ id:'barbell_curl', name_en:'Barbell Curl', name_pl:'Uginanie ramion ze sztangą', body_region:'upper_body', muscle_group:'biceps', primary_muscles:['biceps_brachii'], secondary_muscles:['brachialis','brachioradialis'], movement_pattern:'elbow_flexion', exercise_type:'isolation', equipment:['barbell'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'6-12', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Klasyczne ćwiczenie na biceps — dobra progresja siłowa.', tier_reason:'Mocne ćwiczenie na biceps, ale brak stretch position.', tags:['hypertrophy','strength','barbell','isolation','biceps'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'incline_dumbbell_curl', name_en:'Incline Dumbbell Curl', name_pl:'Uginanie ramion z hantlami na ławce skośnej', body_region:'upper_body', muscle_group:'biceps', primary_muscles:['biceps_brachii'], secondary_muscles:['brachialis'], movement_pattern:'elbow_flexion', exercise_type:'isolation', equipment:['dumbbell'], tier:'S', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:1, stimulus_rating:5, fatigue_rating:2, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Najlepszy stretch bicepsa — kluczowe ćwiczenie na masę.', tier_reason:'Maksymalna pozycja rozciągnięcia bicepsa — S tier na hipertrofię.', tags:['hypertrophy','dumbbell','isolation','biceps','lengthened_bias','stretch_position','high_stimulus'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'cable_curl', name_en:'Cable Curl', name_pl:'Uginanie ramion na wyciągu', body_region:'upper_body', muscle_group:'biceps', primary_muscles:['biceps_brachii'], secondary_muscles:['brachialis'], movement_pattern:'elbow_flexion', exercise_type:'isolation', equipment:['cable'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-15', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Stałe napięcie wyciągu — świetne uzupełnienie do hantli.', tier_reason:'Stałe napięcie przez cały zakres ruchu — bardzo użyteczne.', tags:['hypertrophy','cable','isolation','biceps','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'preacher_curl', name_en:'Preacher Curl', name_pl:'Uginanie ramion na modliszce', body_region:'upper_body', muscle_group:'biceps', primary_muscles:['biceps_brachii'], secondary_muscles:[], movement_pattern:'elbow_flexion', exercise_type:'isolation', equipment:['barbell','dumbbell'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:2, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Krótki zakres z silnym peak contraction — świetny pump.', tier_reason:'Izolacja bez możliwości kompensacji — dobry pump i kontrol.', tags:['hypertrophy','isolation','biceps','pump','shortened_bias'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'hammer_curl', name_en:'Hammer Curl', name_pl:'Uginanie ramion chwytem neutralnym', body_region:'upper_body', muscle_group:'biceps', primary_muscles:['brachialis','brachioradialis'], secondary_muscles:['biceps_brachii'], movement_pattern:'elbow_flexion', exercise_type:'isolation', equipment:['dumbbell'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:1, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'10-15', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Brachialis i brachioradialis — uzupełnia klasyczne uginanie.', tier_reason:'Uderza w mięśnie niedostatecznie trenowane przez supinowane uginania.', tags:['hypertrophy','dumbbell','isolation','brachialis','forearms'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'single_arm_cable_curl', name_en:'Single-Arm Cable Curl', name_pl:'Uginanie ramion na wyciągu jedną ręką', body_region:'upper_body', muscle_group:'biceps', primary_muscles:['biceps_brachii'], secondary_muscles:['brachialis'], movement_pattern:'elbow_flexion', exercise_type:'isolation', equipment:['cable'], tier:'A', role:'pump', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-2', rest_time_seconds:75, description_short:'Unilateralne uginanie — korekcja dysproporcji i pełny zakres.', tier_reason:'Stałe napięcie + unilateral + stretch position.', tags:['hypertrophy','cable','isolation','biceps','unilateral','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low', unilateral:true },

// ═══════════════════════════════════════════════════════
// TRICEPS
// ═══════════════════════════════════════════════════════

{ id:'cable_triceps_pushdown', name_en:'Cable Triceps Pushdown', name_pl:'Prostowanie ramion na wyciągu w dół', body_region:'upper_body', muscle_group:'triceps', primary_muscles:['triceps_lateral','triceps_medial'], secondary_muscles:[], movement_pattern:'elbow_extension', exercise_type:'isolation', equipment:['cable'], tier:'A', role:'accessory', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Klasyczne pushdown — stałe napięcie na boczną i przyśrodkową głowę.', tier_reason:'Stałe napięcie i łatwa progresja, ale brak stretch głowy długiej.', tags:['hypertrophy','cable','isolation','triceps','pump'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'overhead_cable_triceps_extension', name_en:'Overhead Cable Triceps Extension', name_pl:'Prostowanie ramion nad głową na wyciągu', body_region:'upper_body', muscle_group:'triceps', primary_muscles:['triceps_long_head'], secondary_muscles:['triceps_lateral','triceps_medial'], movement_pattern:'elbow_extension', exercise_type:'isolation', equipment:['cable'], tier:'S', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:5, fatigue_rating:2, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Najlepszy stretch głowy długiej tricepsa — S tier dla masy.', tier_reason:'Maksymalna pozycja rozciągnięcia głowy długiej — kluczowe dla masy tricepsa.', tags:['hypertrophy','cable','isolation','triceps','lengthened_bias','stretch_position','long_head'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'overhead_dumbbell_extension', name_en:'Overhead Dumbbell Triceps Extension', name_pl:'Prostowanie ramion z hantlem nad głową', body_region:'upper_body', muscle_group:'triceps', primary_muscles:['triceps_long_head'], secondary_muscles:['triceps_lateral'], movement_pattern:'elbow_extension', exercise_type:'isolation', equipment:['dumbbell'], tier:'A', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-15', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Dobry stretch głowy długiej z hantlem — popularny i skuteczny.', tier_reason:'Stretch long head — dobre ćwiczenie, ale słabsze napięcie niż cable.', tags:['hypertrophy','dumbbell','isolation','triceps','lengthened_bias','long_head'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'close_grip_bench_press', name_en:'Close-Grip Bench Press', name_pl:'Wyciskanie wąskim chwytem', body_region:'upper_body', muscle_group:'triceps', primary_muscles:['triceps'], secondary_muscles:['chest','front_delts'], movement_pattern:'horizontal_push', exercise_type:'compound', equipment:['barbell'], tier:'A', role:'main', difficulty:'intermediate', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:4, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'5-12', recommended_rir:'1-3', rest_time_seconds:150, description_short:'Compound na triceps z dobrą progresją siłową.', tier_reason:'Dobra siła tricepsa, ale wysoki koszt zmęczenia i brak stretch.', tags:['strength','barbell','compound','triceps'], beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'medium' },

{ id:'ez_bar_skullcrusher', name_en:'EZ-Bar Skullcrusher', name_pl:'Łamanie hantlem EZ (Skullcrusher)', body_region:'upper_body', muscle_group:'triceps', primary_muscles:['triceps_long_head','triceps_lateral'], secondary_muscles:[], movement_pattern:'elbow_extension', exercise_type:'isolation', equipment:['barbell'], tier:'A', role:'secondary', difficulty:'intermediate', skill_requirement:3, stability_requirement:2, stimulus_rating:4, fatigue_rating:3, sfr_rating:3, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Klasyczny skullcrusher — dobry stretch, ale ryzyko łokcia.', tier_reason:'Dobry stretch tricepsa, ale ryzyko bólu łokcia przy złej technice.', tags:['hypertrophy','barbell','isolation','triceps','lengthened_bias'], beginner_friendly:false, lower_back_fatigue:'none', joint_risk:'medium' },

// ═══════════════════════════════════════════════════════
// QUADS / CZWOROGŁOWE
// ═══════════════════════════════════════════════════════

{ id:'hack_squat', name_en:'Hack Squat', name_pl:'Hack squat', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quadriceps'], secondary_muscles:['glutes','adductors'], movement_pattern:'squat_pattern', exercise_type:'compound', equipment:['machine'], tier:'S', role:'main', difficulty:'intermediate', skill_requirement:3, stability_requirement:2, stimulus_rating:5, fatigue_rating:4, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'6-15', recommended_rir:'1-3', rest_time_seconds:180, setup:'Ustaw stopy na platformie na szerokość bioder. Plecy przyklejone do oparcia przez cały ruch.', execution:'Schodź kontrolowanie do pełnego zakresu. Wypychaj przez środek stopy bez agresywnego lockoutu.', cues:['Kolana w linii palców','Zejdź głęboko','Nie odbijaj z dołu','Kontroluj ekscentrykę'], common_mistakes:['Za płytki zakres','Odrywanie bioder','Zapadanie kolan','Zbyt szybkie zejście'], description_short:'Najlepsze maszynowe ćwiczenie na czworogłowe z dużym potencjałem hipertroficznym.', tier_reason:'Wysoki bodziec, dobra stabilność, łatwa progresja — S tier.', tags:['hypertrophy','machine','compound','quads','stable','lengthened_bias','high_stimulus','quad_bias'], beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'medium' },

{ id:'pendulum_squat', name_en:'Pendulum Squat', name_pl:'Przysiad wahadłowy (Pendulum Squat)', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quadriceps'], secondary_muscles:['glutes'], movement_pattern:'squat_pattern', exercise_type:'compound', equipment:['machine'], tier:'S', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:1, stimulus_rating:5, fatigue_rating:3, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:150, description_short:'Jeden z najlepszych wyborów na czworogłowe — głęboki zakres, naturalne obciążenie.', tier_reason:'Biomechanicznie doskonałe ćwiczenie z dużym stretch czworogłowych.', tags:['hypertrophy','machine','compound','quads','stable','lengthened_bias','quad_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'leg_press', name_en:'Leg Press', name_pl:'Suwnica / Leg Press', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quadriceps','glutes'], secondary_muscles:['hamstrings','adductors'], movement_pattern:'squat_pattern', exercise_type:'compound', equipment:['machine','leg_press'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:1, stimulus_rating:4, fatigue_rating:4, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-20', recommended_rir:'1-3', rest_time_seconds:150, description_short:'Wszechstronne ćwiczenie — stopy wyżej = pośladki, niżej = czworogłowe.', tier_reason:'Dobry bodziec i stretch — bezpieczniejsza alternatywa dla przysiadu ze sztangą.', tags:['hypertrophy','machine','compound','quads','glutes','stable','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'single_leg_press', name_en:'Single-Leg Press', name_pl:'Suwnica jedną nogą', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quadriceps','glutes'], secondary_muscles:['hamstrings'], movement_pattern:'single_leg_squat', exercise_type:'compound', equipment:['machine','leg_press'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:2, stability_requirement:1, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'10-15', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Unilateralny leg press — korekcja dysproporcji między nogami.', tier_reason:'Dobra izolacja jednostronna z bezpieczeństwem maszyny.', tags:['hypertrophy','machine','compound','quads','unilateral'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low', unilateral:true },

{ id:'leg_extension', name_en:'Leg Extension', name_pl:'Prostowanie nóg na maszynie', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quadriceps'], secondary_muscles:[], movement_pattern:'knee_extension', exercise_type:'isolation', equipment:['machine','leg_extension'], tier:'A', role:'pump', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Izolacja czworogłowych — świetny pump i wykończenie sesji nóg.', tier_reason:'Peak contraction i izolacja — pump i uzupełnienie do compound.', tags:['hypertrophy','machine','isolation','quads','pump','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'medium' },

{ id:'single_leg_extension', name_en:'Single-Leg Extension', name_pl:'Prostowanie nóg jedną nogą', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quadriceps'], secondary_muscles:[], movement_pattern:'knee_extension', exercise_type:'isolation', equipment:['machine'], tier:'A', role:'pump', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-2', rest_time_seconds:75, description_short:'Unilateralny leg extension — korekcja dysproporcji i pełna izolacja.', tier_reason:'Izolacja + unilateral = korekcja stron bez kompensacji.', tags:['hypertrophy','machine','isolation','quads','pump','unilateral'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'medium', unilateral:true },

{ id:'bulgarian_split_squat', name_en:'Bulgarian Split Squat', name_pl:'Przysiad bułgarski', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quadriceps','glutes'], secondary_muscles:['hamstrings','adductors'], movement_pattern:'single_leg_squat', exercise_type:'compound', equipment:['dumbbell','barbell','bodyweight'], tier:'A', role:'main', difficulty:'intermediate', skill_requirement:4, stability_requirement:4, stimulus_rating:5, fatigue_rating:4, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:150, description_short:'Wysoki bodziec unilateralny — kluczowe dla nóg i pośladków.', tier_reason:'Ogromny stretch i bodziec, ale wymaga koordynacji i jest wyczerpujące.', tags:['hypertrophy','strength','dumbbell','compound','quads','glutes','unilateral','lengthened_bias'], beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'medium', unilateral:true },

{ id:'goblet_squat', name_en:'Goblet Squat', name_pl:'Przysiad z kettlebell (Goblet Squat)', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quadriceps','glutes'], secondary_muscles:['core','adductors'], movement_pattern:'squat_pattern', exercise_type:'compound', equipment:['dumbbell'], tier:'B', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:3, stimulus_rating:3, fatigue_rating:3, sfr_rating:3, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'10-20', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Świetny dla nauki techniki przysiadu i mobilności bioder.', tier_reason:'Dobra technika, ale ograniczone obciążenie — głównie dla początkujących.', tags:['beginner_friendly','dumbbell','compound','quads','technique','mobility'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'barbell_squat', name_en:'Back Squat', name_pl:'Przysiad ze sztangą', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quadriceps','glutes'], secondary_muscles:['hamstrings','erectors','adductors'], movement_pattern:'squat_pattern', exercise_type:'compound', equipment:['barbell','squat_rack'], tier:'B', role:'main', difficulty:'advanced', skill_requirement:5, stability_requirement:5, stimulus_rating:5, fatigue_rating:5, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'3-8', recommended_rir:'1-3', rest_time_seconds:240, description_short:'Król ćwiczeń nóg — ale wysoka cena zmęczenia.', tier_reason:'Świetny na siłę, ale dla hipertrofii jest wiele lepszych opcji z wyższym SFR.', tags:['strength','barbell','compound','quads','high_fatigue','advanced'], beginner_friendly:false, lower_back_fatigue:'high', joint_risk:'high' },

{ id:'reverse_lunge', name_en:'Reverse Lunge', name_pl:'Wykroki w tył', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quads','glutes'], secondary_muscles:['hamstrings','adductors'], movement_pattern:'single_leg_squat', exercise_type:'compound', equipment:['dumbbell','barbell','bodyweight'], tier:'B', role:'secondary', difficulty:'beginner', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:3, sfr_rating:3, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'10-15', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Wykrok wsteczny — bezpieczniejszy od przedniego dla kolana.', tier_reason:'Dobre ćwiczenie, ale mniej stabilne i trudniejsze w progresji.', tags:['hypertrophy','compound','quads','glutes','unilateral'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low', unilateral:true },

{ id:'step_up', name_en:'Step-Up', name_pl:'Wejście na podwyższenie', body_region:'lower_body', muscle_group:'quads', primary_muscles:['quads','glutes'], secondary_muscles:['hamstrings'], movement_pattern:'single_leg_squat', exercise_type:'compound', equipment:['dumbbell','bodyweight'], tier:'B', role:'secondary', difficulty:'beginner', skill_requirement:2, stability_requirement:3, stimulus_rating:3, fatigue_rating:2, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'10-20', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Funkcjonalne ćwiczenie unilateralne — dobre uzupełnienie do nóg.', tier_reason:'Użyteczne ale ograniczone obciążenie — dobry wybór dla starszych klientów.', tags:['functional','compound','quads','glutes','unilateral','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low', unilateral:true },

// ═══════════════════════════════════════════════════════
// HAMSTRINGS / DWUGŁOWE UDA
// ═══════════════════════════════════════════════════════

{ id:'romanian_deadlift', name_en:'Romanian Deadlift', name_pl:'Martwy ciąg rumuński (RDL)', body_region:'lower_body', muscle_group:'hamstrings', primary_muscles:['hamstrings','glutes'], secondary_muscles:['erectors','adductors','upper_back'], movement_pattern:'hip_hinge', exercise_type:'compound', equipment:['barbell'], tier:'S', role:'main', difficulty:'intermediate', skill_requirement:4, stability_requirement:4, stimulus_rating:5, fatigue_rating:4, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'6-12', recommended_rir:'1-3', rest_time_seconds:180, setup:'Stań stabilnie, sztanga blisko ud. Kolana lekko ugięte, brzuch napięty, plecy neutralne.', execution:'Cofaj biodra w tył, prowadząc sztangę blisko ciała. Schodź do momentu mocnego rozciągnięcia dwójek.', cues:['Biodra w tył','Sztanga blisko nóg','Czuj rozciągnięcie dwójek','Żebra schowane'], common_mistakes:['Za duże ugięcie kolan','Zaokrąglanie pleców','Oddalanie sztangi od ciała'], description_short:'Kluczowe ćwiczenie na dwugłowe i pośladki w wydłużonej pozycji.', tier_reason:'Bardzo silny bodziec hipertroficzny dla tylnej taśmy.', tags:['hypertrophy','barbell','compound','hamstrings','glutes','hip_hinge','lengthened_bias','high_stimulus'], beginner_friendly:false, lower_back_fatigue:'medium', joint_risk:'medium' },

{ id:'dumbbell_rdl', name_en:'Dumbbell Romanian Deadlift', name_pl:'Martwy ciąg rumuński z hantlami', body_region:'lower_body', muscle_group:'hamstrings', primary_muscles:['hamstrings','glutes'], secondary_muscles:['erectors'], movement_pattern:'hip_hinge', exercise_type:'compound', equipment:['dumbbell'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:150, description_short:'RDL z hantlami — łatwiejszy do nauki niż wersja ze sztangą.', tier_reason:'Prawie identyczny bodziec jak barbell RDL, ale łatwiejszy technicznie.', tags:['hypertrophy','dumbbell','compound','hamstrings','hip_hinge','lengthened_bias','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'medium', joint_risk:'low' },

{ id:'single_leg_rdl', name_en:'Single-Leg Romanian Deadlift', name_pl:'Martwy ciąg rumuński na jednej nodze', body_region:'lower_body', muscle_group:'hamstrings', primary_muscles:['hamstrings','glutes'], secondary_muscles:['erectors','adductors'], movement_pattern:'hip_hinge', exercise_type:'compound', equipment:['dumbbell','barbell'], tier:'A', role:'secondary', difficulty:'intermediate', skill_requirement:4, stability_requirement:5, stimulus_rating:4, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-12', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Unilateralny RDL — korekcja dysproporcji i koordynacja.', tier_reason:'Duży bodziec + korekcja dysproporcji + propriocepcja.', tags:['hypertrophy','dumbbell','compound','hamstrings','unilateral','lengthened_bias'], beginner_friendly:false, lower_back_fatigue:'medium', joint_risk:'medium', unilateral:true },

{ id:'seated_leg_curl', name_en:'Seated Leg Curl', name_pl:'Uginanie nóg siedząc (Leg Curl)', body_region:'lower_body', muscle_group:'hamstrings', primary_muscles:['hamstrings'], secondary_muscles:[], movement_pattern:'knee_flexion', exercise_type:'isolation', equipment:['machine'], tier:'S', role:'secondary', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:5, fatigue_rating:2, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'8-15', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Najlepsze izolowane ćwiczenie na dwugłowe — stretch w biodrach i kolanie.', tier_reason:'Seated > Lying: biodra zgięte = lepszy stretch hamstrings. S tier.', tags:['hypertrophy','machine','isolation','hamstrings','lengthened_bias','stretch_position','high_stimulus'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'lying_leg_curl', name_en:'Lying Leg Curl', name_pl:'Uginanie nóg leżąc (Leg Curl)', body_region:'lower_body', muscle_group:'hamstrings', primary_muscles:['hamstrings'], secondary_muscles:[], movement_pattern:'knee_flexion', exercise_type:'isolation', equipment:['machine'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'8-15', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Klasyczne uginanie nóg leżąc — mniej stretch niż seated, ale popularny wybór.', tier_reason:'Dobry, ale gorszy stretch niż seated leg curl.', tags:['hypertrophy','machine','isolation','hamstrings'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'single_leg_curl', name_en:'Single-Leg Curl', name_pl:'Uginanie nóg jedną nogą', body_region:'lower_body', muscle_group:'hamstrings', primary_muscles:['hamstrings'], secondary_muscles:[], movement_pattern:'knee_flexion', exercise_type:'isolation', equipment:['machine'], tier:'A', role:'pump', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-15', recommended_rir:'0-2', rest_time_seconds:75, description_short:'Unilateralne uginanie nóg — korekcja dysproporcji.', tier_reason:'Stretch + unilateral + brak kompensacji słabszą nogą.', tags:['hypertrophy','machine','isolation','hamstrings','unilateral'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low', unilateral:true },

{ id:'nordic_curl', name_en:'Nordic Hamstring Curl', name_pl:'Nordic curl (Uginanie nóg norweskie)', body_region:'lower_body', muscle_group:'hamstrings', primary_muscles:['hamstrings'], secondary_muscles:['glutes'], movement_pattern:'knee_flexion', exercise_type:'compound', equipment:['bodyweight'], tier:'A', role:'prehab', difficulty:'advanced', skill_requirement:5, stability_requirement:4, stimulus_rating:5, fatigue_rating:4, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'3-8', recommended_rir:'2-3', rest_time_seconds:150, description_short:'Ekscentryczna siła dwugłowych — prewencja kontuzji i siła.', tier_reason:'Wysoce specyficzne i trudne — świetne dla sportowców i prewencji kontuzji.', tags:['strength','prehab','bodyweight','hamstrings','eccentric','advanced'], beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'medium' },

// ═══════════════════════════════════════════════════════
// GLUTES / POŚLADKI
// ═══════════════════════════════════════════════════════

{ id:'hip_thrust_barbell', name_en:'Barbell Hip Thrust', name_pl:'Hip thrust ze sztangą', body_region:'lower_body', muscle_group:'glutes', primary_muscles:['glutes'], secondary_muscles:['hamstrings','adductors','quads'], movement_pattern:'hip_extension', exercise_type:'compound', equipment:['barbell'], tier:'S', role:'main', difficulty:'intermediate', skill_requirement:3, stability_requirement:2, stimulus_rating:5, fatigue_rating:3, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'8-20', recommended_rir:'0-3', rest_time_seconds:120, setup:'Usiądź plecami przy ławce, sztanga na biodrach. Stopy na szerokość bioder, kolana 90° w górze.', execution:'Unoś biodra do pełnego wyprostu, ściskając pośladki w górze. Kontroluj zejście.', cues:['Ściskaj pośladki w górze','Podbródek na klatce','Kolana nie zapadają','Pełny wyprost bioder'], common_mistakes:['Zbyt duże wygięcie lędźwi','Kolana zapadają','Za szybkie tempo','Brak pełnego wyprostu'], description_short:'Najlepsze ćwiczenie na pośladki — kluczowe dla każdego planu.', tier_reason:'Maksymalna aktywacja pośladków, świetny stretch — bezapelacyjny S tier.', tags:['hypertrophy','barbell','compound','glutes','hip_extension','lengthened_bias','high_stimulus','glute_bias'], beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'hip_thrust_machine', name_en:'Machine Hip Thrust', name_pl:'Hip thrust na maszynie', body_region:'lower_body', muscle_group:'glutes', primary_muscles:['glutes'], secondary_muscles:['hamstrings'], movement_pattern:'hip_extension', exercise_type:'compound', equipment:['machine'], tier:'S', role:'main', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:5, fatigue_rating:3, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:120, description_short:'Hip thrust na maszynie — bezpieczniejszy i łatwiejszy setup niż ze sztangą.', tier_reason:'Identyczny bodziec jak barbell, ale łatwiej ustawić i progresować.', tags:['hypertrophy','machine','compound','glutes','stable','beginner_friendly','glute_bias'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'dumbbell_hip_thrust', name_en:'Dumbbell Hip Thrust', name_pl:'Hip thrust z hantlem', body_region:'lower_body', muscle_group:'glutes', primary_muscles:['glutes'], secondary_muscles:['hamstrings'], movement_pattern:'hip_extension', exercise_type:'compound', equipment:['dumbbell'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Hip thrust z hantlem — dobra opcja gdy nie ma maszyny ani sztangi.', tier_reason:'Dobry bodziec, łatwy setup — ale ograniczone obciążenie.', tags:['hypertrophy','dumbbell','compound','glutes','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'glute_bridge', name_en:'Glute Bridge', name_pl:'Mostek pośladkowy', body_region:'lower_body', muscle_group:'glutes', primary_muscles:['glutes'], secondary_muscles:['hamstrings'], movement_pattern:'hip_extension', exercise_type:'compound', equipment:['bodyweight','barbell'], tier:'B', role:'secondary', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:3, fatigue_rating:1, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'15-25', recommended_rir:'0-3', rest_time_seconds:75, description_short:'Podstawowa aktywacja pośladków — dobry warm-up lub dla początkujących.', tier_reason:'Ograniczone obciążenie — użyteczne jako aktywacja lub dla osób starszych.', tags:['beginner_friendly','bodyweight','glutes','activation','prehab'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'single_leg_hip_thrust', name_en:'Single-Leg Hip Thrust', name_pl:'Hip thrust na jednej nodze', body_region:'lower_body', muscle_group:'glutes', primary_muscles:['glutes'], secondary_muscles:['hamstrings'], movement_pattern:'hip_extension', exercise_type:'compound', equipment:['bodyweight','dumbbell'], tier:'A', role:'secondary', difficulty:'intermediate', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'10-15', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Unilateralny hip thrust — korekcja dysproporcji pośladków.', tier_reason:'Dobra izolacja jednostronna z dużym bodźcem dla pośladków.', tags:['hypertrophy','bodyweight','glutes','unilateral','glute_bias'], beginner_friendly:false, lower_back_fatigue:'none', joint_risk:'low', unilateral:true },

{ id:'cable_kickback', name_en:'Cable Glute Kickback', name_pl:'Odpychanie nogi w tył na wyciągu', body_region:'lower_body', muscle_group:'glutes', primary_muscles:['glutes'], secondary_muscles:['hamstrings'], movement_pattern:'hip_extension', exercise_type:'isolation', equipment:['cable'], tier:'B', role:'pump', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:3, fatigue_rating:1, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'15-25', recommended_rir:'0-2', rest_time_seconds:75, description_short:'Izolacja pośladków — dobra jako uzupełnienie do hip thrust.', tier_reason:'Niski SFR — użyteczne jako pump/wykończenie, nie jako główne ćwiczenie.', tags:['pump','cable','isolation','glutes','unilateral'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low', unilateral:true },

{ id:'abduction_machine', name_en:'Hip Abduction Machine', name_pl:'Odwodzenie nóg na maszynie', body_region:'lower_body', muscle_group:'glutes', primary_muscles:['glute_medius','glute_minimus'], secondary_muscles:[], movement_pattern:'hip_abduction', exercise_type:'isolation', equipment:['machine'], tier:'A', role:'accessory', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:1, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'15-25', recommended_rir:'0-3', rest_time_seconds:75, description_short:'Izolacja środkowego pośladka — pomijana, ale ważna dla kobiet.', tier_reason:'Jedyne proste ćwiczenie na glute medius — A tier dla kobiet.', tags:['hypertrophy','machine','isolation','glute_medius','glute_bias','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'cable_pull_through', name_en:'Cable Pull-Through', name_pl:'Przeciąganie liny przez nogi na wyciągu', body_region:'lower_body', muscle_group:'glutes', primary_muscles:['glutes','hamstrings'], secondary_muscles:['erectors'], movement_pattern:'hip_hinge', exercise_type:'compound', equipment:['cable'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Hip hinge z wyciągiem — świetny stretch pośladków i dwugłowych.', tier_reason:'Stałe napięcie cable + stretch pośladków — lepszy SFR niż martwy ciąg.', tags:['hypertrophy','cable','compound','glutes','hamstrings','hip_hinge','lengthened_bias'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

// ═══════════════════════════════════════════════════════
// CALVES / ŁYDKI
// ═══════════════════════════════════════════════════════

{ id:'standing_calf_raise', name_en:'Standing Calf Raise', name_pl:'Wspięcia na palce stojąc', body_region:'lower_body', muscle_group:'calves', primary_muscles:['gastrocnemius'], secondary_muscles:['soleus'], movement_pattern:'calf_raise', exercise_type:'isolation', equipment:['machine','barbell','bodyweight'], tier:'A', role:'main', difficulty:'beginner', skill_requirement:1, stability_requirement:2, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Głowa przyśrodkowa i boczna brzuchatego — standard łydek.', tier_reason:'Dobry bodziec na gastrocnemius z pełnym stretchem.', tags:['hypertrophy','machine','isolation','calves','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'seated_calf_raise', name_en:'Seated Calf Raise', name_pl:'Wspięcia na palce siedząc', body_region:'lower_body', muscle_group:'calves', primary_muscles:['soleus'], secondary_muscles:['gastrocnemius'], movement_pattern:'calf_raise', exercise_type:'isolation', equipment:['machine'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Izolacja soleus — zgięte kolano = gastrocnemius odpada.', tier_reason:'Jedyne efektywne ćwiczenie na soleus — uzupełnienie do stojącego.', tags:['hypertrophy','machine','isolation','calves','soleus','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'single_leg_calf_raise', name_en:'Single-Leg Calf Raise', name_pl:'Wspięcia na palce na jednej nodze', body_region:'lower_body', muscle_group:'calves', primary_muscles:['gastrocnemius','soleus'], secondary_muscles:[], movement_pattern:'calf_raise', exercise_type:'isolation', equipment:['bodyweight','dumbbell'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:2, stability_requirement:3, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:75, description_short:'Unilateralne wspięcia — pełny zakres i korekcja dysproporcji.', tier_reason:'Większy stretch i zakres niż oburącz + korekcja stron.', tags:['hypertrophy','bodyweight','isolation','calves','unilateral'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low', unilateral:true },

{ id:'leg_press_calf_raise', name_en:'Leg Press Calf Raise', name_pl:'Wspięcia na palce na suwnicy', body_region:'lower_body', muscle_group:'calves', primary_muscles:['gastrocnemius'], secondary_muscles:[], movement_pattern:'calf_raise', exercise_type:'isolation', equipment:['machine','leg_press'], tier:'B', role:'pump', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:3, fatigue_rating:1, sfr_rating:3, stretch_position:true, lengthened_bias:false, compound:false, recommended_rep_range:'15-25', recommended_rir:'0-2', rest_time_seconds:75, description_short:'Wspięcia na suwnicy — wygodna opcja bez dodatkowej maszyny.', tier_reason:'Użyteczne jako uzupełnienie, ale gorszy stretch niż dedykowana maszyna.', tags:['hypertrophy','machine','isolation','calves','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

// ═══════════════════════════════════════════════════════
// CORE / BRZUCH
// ═══════════════════════════════════════════════════════

{ id:'cable_crunch', name_en:'Cable Crunch', name_pl:'Spięcia brzucha na wyciągu', body_region:'core', muscle_group:'abs', primary_muscles:['rectus_abdominis'], secondary_muscles:['obliques'], movement_pattern:'spinal_flexion', exercise_type:'isolation', equipment:['cable'], tier:'S', role:'main', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:5, fatigue_rating:2, sfr_rating:5, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90, description_short:'Najlepsze ćwiczenie na brzuch — stałe napięcie, łatwa progresja.', tier_reason:'Progresja przez ciężar + stretch pozycja = S tier na brzuch.', tags:['hypertrophy','cable','isolation','abs','lengthened_bias','high_stimulus'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'hanging_leg_raise', name_en:'Hanging Leg Raise', name_pl:'Unoszenie nóg w zwisie', body_region:'core', muscle_group:'abs', primary_muscles:['rectus_abdominis_lower','hip_flexors'], secondary_muscles:['obliques'], movement_pattern:'hip_flexion', exercise_type:'isolation', equipment:['bodyweight'], tier:'A', role:'secondary', difficulty:'intermediate', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Dolna część brzucha i zginacze biodra — świetne ćwiczenie w zwisie.', tier_reason:'Duży zakres ruchu i stretch dolnej części brzucha.', tags:['hypertrophy','bodyweight','abs','lower_abs','lengthened_bias'], beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'decline_crunch', name_en:'Decline Crunch', name_pl:'Spięcia na ławce skośnej ujemnej', body_region:'core', muscle_group:'abs', primary_muscles:['rectus_abdominis'], secondary_muscles:['hip_flexors'], movement_pattern:'spinal_flexion', exercise_type:'isolation', equipment:['bodyweight'], tier:'B', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:3, fatigue_rating:2, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'12-20', recommended_rir:'1-3', rest_time_seconds:75, description_short:'Spięcia ze zwiększonym zakresem — lepsze od klasycznych na podłodze.', tier_reason:'Dobry zakres ruchu, ale gorszy od cable crunch w progresji.', tags:['hypertrophy','bodyweight','abs','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low' },

{ id:'ab_wheel_rollout', name_en:'Ab Wheel Rollout', name_pl:'Rollout kołem do brzucha', body_region:'core', muscle_group:'abs', primary_muscles:['rectus_abdominis'], secondary_muscles:['lats','obliques','erectors'], movement_pattern:'anti_extension', exercise_type:'compound', equipment:['bodyweight'], tier:'A', role:'main', difficulty:'intermediate', skill_requirement:4, stability_requirement:5, stimulus_rating:5, fatigue_rating:3, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:true, recommended_rep_range:'5-12', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Anty-extensja core — ogromny bodziec przy minimalnym sprzęcie.', tier_reason:'Jeden z najsilniejszych bodźców dla core — wymagający ale efektywny.', tags:['hypertrophy','bodyweight','abs','anti_extension','advanced','lengthened_bias'], beginner_friendly:false, lower_back_fatigue:'medium', joint_risk:'medium' },

{ id:'plank', name_en:'Plank', name_pl:'Deska (Plank)', body_region:'core', muscle_group:'abs', primary_muscles:['rectus_abdominis','transverse_abdominis'], secondary_muscles:['obliques','erectors'], movement_pattern:'anti_extension', exercise_type:'isolation', equipment:['bodyweight'], tier:'B', role:'prehab', difficulty:'beginner', skill_requirement:2, stability_requirement:3, stimulus_rating:3, fatigue_rating:1, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'20-60s', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Klasyczna izometria core — dobra baza i aktywacja.', tier_reason:'Dobra aktywacja core, ale ograniczona progresja — prehab/aktywacja.', tags:['prehab','bodyweight','abs','isometric','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'hollow_body_hold', name_en:'Hollow Body Hold', name_pl:'Izometria tułowia (Hollow Body)', body_region:'core', muscle_group:'abs', primary_muscles:['rectus_abdominis','transverse_abdominis'], secondary_muscles:['hip_flexors'], movement_pattern:'anti_extension', exercise_type:'isolation', equipment:['bodyweight'], tier:'A', role:'prehab', difficulty:'intermediate', skill_requirement:3, stability_requirement:3, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'20-40s', recommended_rir:'1-3', rest_time_seconds:90, description_short:'Zaawansowana izometria — lepsza niż deska pod kontrolę core.', tier_reason:'Lepsza aktywacja niż plank z dłuższym momentem ramienia sił.', tags:['prehab','bodyweight','abs','isometric','core_control'], beginner_friendly:false, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'machine_crunch', name_en:'Machine Crunch', name_pl:'Spięcia brzucha na maszynie', body_region:'core', muscle_group:'abs', primary_muscles:['rectus_abdominis'], secondary_muscles:[], movement_pattern:'spinal_flexion', exercise_type:'isolation', equipment:['machine'], tier:'A', role:'secondary', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:4, fatigue_rating:2, sfr_rating:4, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:75, description_short:'Spięcia na maszynie — dobra alternatywa dla cable crunch.', tier_reason:'Stałe napięcie i stretch — prawie tak dobry jak cable crunch.', tags:['hypertrophy','machine','isolation','abs','beginner_friendly'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

// ═══════════════════════════════════════════════════════
// FOREARMS / PRZEDRAMIONA
// ═══════════════════════════════════════════════════════

{ id:'barbell_wrist_curl', name_en:'Barbell Wrist Curl', name_pl:'Zginanie nadgarstków ze sztangą', body_region:'upper_body', muscle_group:'forearms', primary_muscles:['wrist_flexors'], secondary_muscles:[], movement_pattern:'elbow_extension', exercise_type:'isolation', equipment:['barbell'], tier:'B', role:'accessory', difficulty:'beginner', skill_requirement:1, stability_requirement:1, stimulus_rating:3, fatigue_rating:1, sfr_rating:3, stretch_position:true, lengthened_bias:true, compound:false, recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:60, description_short:'Zginanie nadgarstków — izolacja zginaczy przedramienia.', tier_reason:'Użyteczne ale niszowe — dobry carry-over z ćwiczeń podstawowych.', tags:['isolation','forearms','barbell'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'reverse_curl', name_en:'Reverse Curl', name_pl:'Uginanie ramion odwróconym chwytem', body_region:'upper_body', muscle_group:'forearms', primary_muscles:['brachioradialis','wrist_extensors'], secondary_muscles:['biceps_brachii'], movement_pattern:'elbow_flexion', exercise_type:'isolation', equipment:['barbell','cable'], tier:'B', role:'accessory', difficulty:'beginner', skill_requirement:2, stability_requirement:2, stimulus_rating:3, fatigue_rating:2, sfr_rating:3, stretch_position:false, lengthened_bias:false, compound:false, recommended_rep_range:'10-15', recommended_rir:'1-3', rest_time_seconds:75, description_short:'Brachioradialis i prostowniki nadgarstka — uzupełnienie do hammer curl.', tier_reason:'Uzupełnia uginania — trafia w zaniedbane partie przedramion.', tags:['isolation','forearms','barbell','cable'], beginner_friendly:true, lower_back_fatigue:'none', joint_risk:'low' },

{ id:'farmers_carry', name_en:'Farmer\'s Carry', name_pl:'Spacer farmera (Farmer\'s Carry)', body_region:'upper_body', muscle_group:'forearms', primary_muscles:['forearms','grip'], secondary_muscles:['traps','core','quads','glutes'], movement_pattern:'loaded_carry', exercise_type:'compound', equipment:['dumbbell','barbell'], tier:'A', role:'conditioning', difficulty:'beginner', skill_requirement:2, stability_requirement:4, stimulus_rating:4, fatigue_rating:4, sfr_rating:4, stretch_position:false, lengthened_bias:false, compound:true, recommended_rep_range:'20-40m', recommended_rir:'1-3', rest_time_seconds:120, description_short:'Jeden z najlepszych ćwiczeń funkcjonalnych — grip, tułów, wszystko.', tier_reason:'Ogromne benefity przy prostym wykonaniu — grip, core, kondycja.', tags:['functional','compound','forearms','grip','conditioning','core'], beginner_friendly:true, lower_back_fatigue:'medium', joint_risk:'low' },

]

async function seedExercises() {
  console.log(`Seeding ${EXERCISES.length} exercises...`)

  for (const exercise of EXERCISES) {
    const { error } = await supabase
      .from('exercises')
      .upsert(exercise, { onConflict: 'id' })

    if (error) {
      console.error(`Error seeding ${exercise.id}:`, error.message)
    } else {
      console.log(`✓ ${exercise.name_pl}`)
    }
  }

  console.log('Done!')
}

seedExercises()
