const { createClient } = require('@supabase/supabase-js')
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

const EXERCISES = [

// ═══════════════════════════════════════════
// CHEST
// ═══════════════════════════════════════════
{
  id:'barbell_bench_press', name_en:'Barbell Bench Press', name_pl:'Wyciskanie sztangi leżąc',
  body_region:'upper_body', muscle_group:'chest',
  primary_muscles:['chest'], secondary_muscles:['triceps','front_delts'],
  movement_pattern:'horizontal_push', exercise_type:'compound', equipment:['barbell'],
  tier:'A', role:'main', difficulty:'intermediate',
  skill_requirement:3, stability_requirement:3,
  stimulus_rating:4, fatigue_rating:4, sfr_rating:4,
  systemic_fatigue:3, local_fatigue:4, joint_stress:3, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:5,conditioning:2,rehab:1},
  specificity_rating:{hypertrophy:4,strength:5,general_fitness:4},
  stretch_position:false, lengthened_bias:false, compound:true,
  recommended_rep_range:'4-10', recommended_rir:'1-3', rest_time_seconds:180,
  description_short:'Klasyczne ćwiczenie na klatkę z dużym potencjałem siłowym.',
  tier_reason:'Silny bodziec ale gorszy stretch niż DB/cable.',
  client_fit_notes:'Świetny dla klientów z dobrą mobilnością barku i techniką. Może być problematyczny przy bólu barku lub słabej mobilności.',
  selection_logic:'Wybierz gdy cel to siła lub klient lubi wolne ciężary. Dla samej hipertrofii rozważ DB lub cable jako uzupełnienie.',
  tags:['hypertrophy','strength','barbell','compound','chest'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'medium'
},
{
  id:'dumbbell_bench_press', name_en:'Dumbbell Bench Press', name_pl:'Wyciskanie hantli leżąc',
  body_region:'upper_body', muscle_group:'chest',
  primary_muscles:['chest'], secondary_muscles:['triceps','front_delts'],
  movement_pattern:'horizontal_push', exercise_type:'compound', equipment:['dumbbell'],
  tier:'A', role:'main', difficulty:'beginner',
  skill_requirement:2, stability_requirement:3,
  stimulus_rating:4, fatigue_rating:3, sfr_rating:4,
  systemic_fatigue:2, local_fatigue:4, joint_stress:2, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:3,conditioning:2,rehab:2},
  specificity_rating:{hypertrophy:4,strength:3,general_fitness:4},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:150,
  description_short:'Większy zakres ruchu niż sztanga, lepszy stretch klatki.',
  tier_reason:'Lepsza pozycja rozciągnięcia niż barbell, bezpieczniejszy dla barku.',
  client_fit_notes:'Dobry dla większości klientów — większy zakres ruchu i mniejszy stres na bark niż sztanga.',
  selection_logic:'Wybierz gdy priorytet to hipertrofia klatki z pełnym zakresem ruchu.',
  tags:['hypertrophy','dumbbell','compound','chest','lengthened_bias'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'machine_chest_press', name_en:'Machine Chest Press', name_pl:'Wyciskanie na maszynie poziomej',
  body_region:'upper_body', muscle_group:'chest',
  primary_muscles:['chest'], secondary_muscles:['triceps','front_delts'],
  movement_pattern:'horizontal_push', exercise_type:'compound', equipment:['machine'],
  tier:'A', role:'main', difficulty:'beginner',
  skill_requirement:1, stability_requirement:1,
  stimulus_rating:4, fatigue_rating:2, sfr_rating:4,
  systemic_fatigue:1, local_fatigue:4, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:2,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:4,strength:2,general_fitness:4},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'8-20', recommended_rir:'0-3', rest_time_seconds:120,
  description_short:'Stabilne wyciskanie na maszynie — idealne dla początkujących i pump setów.',
  tier_reason:'Dobry bodziec, stałe napięcie, bezpieczny dla barku.',
  client_fit_notes:'Idealny dla początkujących, starszych klientów lub rehabilitacji barku.',
  selection_logic:'Wybierz gdy klient potrzebuje stabilności, bezpieczeństwa lub jest po kontuzji barku.',
  tags:['hypertrophy','machine','stable','chest','beginner_friendly'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'incline_dumbbell_press', name_en:'Incline Dumbbell Press', name_pl:'Wyciskanie hantli na ławce skośnej',
  body_region:'upper_body', muscle_group:'chest',
  primary_muscles:['chest_upper'], secondary_muscles:['triceps','front_delts'],
  movement_pattern:'incline_push', exercise_type:'compound', equipment:['dumbbell'],
  tier:'A', role:'main', difficulty:'beginner',
  skill_requirement:2, stability_requirement:3,
  stimulus_rating:4, fatigue_rating:3, sfr_rating:4,
  systemic_fatigue:2, local_fatigue:4, joint_stress:2, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:3,conditioning:1,rehab:2},
  specificity_rating:{hypertrophy:4,strength:3,general_fitness:4},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:150,
  description_short:'Jeden z najlepszych wyborów na górną część klatki ze stretch position.',
  tier_reason:'Lepsza pozycja rozciągnięcia niż barbell incline, bezpieczniejszy.',
  client_fit_notes:'Dobry dla większości — szczególnie polecany zamiast incline barbell press.',
  selection_logic:'Wybierz gdy priorytet to górna klatka z zachowaniem bezpieczeństwa barku.',
  tags:['hypertrophy','dumbbell','chest_upper','incline','lengthened_bias'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'cable_fly', name_en:'Cable Fly', name_pl:'Rozpiętki na wyciągu',
  body_region:'upper_body', muscle_group:'chest',
  primary_muscles:['chest'], secondary_muscles:[],
  movement_pattern:'fly_adduction', exercise_type:'isolation', equipment:['cable'],
  tier:'S', role:'accessory', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:5, fatigue_rating:2, sfr_rating:5,
  systemic_fatigue:1, local_fatigue:4, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:5,strength:1,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:5,strength:1,general_fitness:3},
  stretch_position:true, lengthened_bias:true, compound:false,
  recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90,
  description_short:'Najlepsze ćwiczenie izolowane na klatkę — stałe napięcie i stretch.',
  tier_reason:'Najwyższy SFR dla klatki — stretch position + stałe napięcie cable.',
  client_fit_notes:'Pasuje dla prawie każdego klienta. Brak ryzyka stawowego, łatwa kontrola.',
  selection_logic:'Wybierz jako uzupełnienie do press lub gdy chcesz odciąć triceps od treningu klatki.',
  tags:['hypertrophy','cable','isolation','chest','lengthened_bias','high_stimulus','low_fatigue'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'pec_deck', name_en:'Pec Deck', name_pl:'Rozpiętki na maszynie (Pec Deck)',
  body_region:'upper_body', muscle_group:'chest',
  primary_muscles:['chest'], secondary_muscles:[],
  movement_pattern:'fly_adduction', exercise_type:'isolation', equipment:['machine'],
  tier:'A', role:'accessory', difficulty:'beginner',
  skill_requirement:1, stability_requirement:1,
  stimulus_rating:4, fatigue_rating:2, sfr_rating:4,
  systemic_fatigue:1, local_fatigue:4, joint_stress:2, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:1,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:4,strength:1,general_fitness:3},
  stretch_position:true, lengthened_bias:true, compound:false,
  recommended_rep_range:'10-20', recommended_rir:'0-3', rest_time_seconds:90,
  description_short:'Stabilna maszyna do izolacji klatki, dobra dla początkujących.',
  tier_reason:'Dobry bodziec, stabilna — stałe napięcie słabsze niż cable.',
  client_fit_notes:'Świetny dla osób z bólem barku — stabilna trajektoria. Dobra alternatywa dla cable fly.',
  selection_logic:'Wybierz gdy cable jest zajęty lub klient potrzebuje stabilniejszej opcji.',
  tags:['hypertrophy','machine','isolation','chest','stable','beginner_friendly'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'chest_dips', name_en:'Chest Dips', name_pl:'Dipy na klatkę piersiową',
  body_region:'upper_body', muscle_group:'chest',
  primary_muscles:['chest_lower'], secondary_muscles:['triceps','front_delts'],
  movement_pattern:'incline_push', exercise_type:'compound', equipment:['bodyweight'],
  tier:'B', role:'secondary', difficulty:'intermediate',
  skill_requirement:3, stability_requirement:3,
  stimulus_rating:4, fatigue_rating:3, sfr_rating:3,
  systemic_fatigue:2, local_fatigue:4, joint_stress:3, lower_back_stress:1,
  sfr_context:{hypertrophy:3,strength:4,conditioning:2,rehab:1},
  specificity_rating:{hypertrophy:3,strength:4,general_fitness:4},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120,
  description_short:'Dipy z tułowiem pochylonym — akcentuje dolną część klatki.',
  tier_reason:'Dobry stretch, ale ryzyko barku przy złej technice.',
  client_fit_notes:'Nie dla klientów z historią bólu barku. Wymaga dobrej mobilności.',
  selection_logic:'Wybierz gdy klient ma dobrą technikę i brak problemów ze stawami barkowymi.',
  tags:['hypertrophy','bodyweight','chest_lower','compound'],
  beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'medium'
},
{
  id:'single_arm_cable_fly', name_en:'Single-Arm Cable Fly', name_pl:'Rozpiętki na wyciągu jedną ręką',
  body_region:'upper_body', muscle_group:'chest',
  primary_muscles:['chest'], secondary_muscles:[],
  movement_pattern:'fly_adduction', exercise_type:'isolation', equipment:['cable'],
  tier:'A', role:'pump', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:4, fatigue_rating:2, sfr_rating:4,
  systemic_fatigue:1, local_fatigue:3, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:1,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:4,strength:1,general_fitness:3},
  stretch_position:true, lengthened_bias:true, compound:false,
  recommended_rep_range:'12-20', recommended_rir:'0-2', rest_time_seconds:75,
  description_short:'Unilateralna wersja — dobra do korekcji dysproporcji.',
  tier_reason:'Stretch i napięcie jak cable fly, plus korekcja stron.',
  client_fit_notes:'Dobry gdy jedna strona klatki jest słabsza lub większa.',
  selection_logic:'Wybierz gdy jest asymetria klatki lub jako uzupełnienie pump setów.',
  tags:['hypertrophy','cable','isolation','chest','unilateral'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low', unilateral:true
},

// ═══════════════════════════════════════════
// BACK
// ═══════════════════════════════════════════
{
  id:'lat_pulldown', name_en:'Lat Pulldown', name_pl:'Ściąganie drążka wyciągu górnego',
  body_region:'upper_body', muscle_group:'back',
  primary_muscles:['lats'], secondary_muscles:['biceps','rear_delts'],
  movement_pattern:'vertical_pull', exercise_type:'compound', equipment:['cable','lat_pulldown'],
  tier:'S', role:'main', difficulty:'beginner',
  skill_requirement:2, stability_requirement:1,
  stimulus_rating:5, fatigue_rating:3, sfr_rating:5,
  systemic_fatigue:2, local_fatigue:4, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:5,strength:3,conditioning:2,rehab:3},
  specificity_rating:{hypertrophy:5,strength:3,general_fitness:4},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120,
  description_short:'Najlepsze ćwiczenie na szerokie plecy dla większości klientów.',
  tier_reason:'Stałe napięcie cable, stretch latissimus, łatwa progresja — S tier.',
  client_fit_notes:'Pasuje dla prawie każdego. Lepsza alternatywa niż podciąganie dla początkujących.',
  selection_logic:'Domyślny wybór na vertical pull dla większości klientów z celami hipertroficznymi.',
  tags:['hypertrophy','cable','compound','lats','vertical_pull','beginner_friendly','lengthened_bias'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'pull_up', name_en:'Pull-up', name_pl:'Podciąganie na drążku',
  body_region:'upper_body', muscle_group:'back',
  primary_muscles:['lats','biceps'], secondary_muscles:['rear_delts','rhomboids'],
  movement_pattern:'vertical_pull', exercise_type:'compound', equipment:['bodyweight'],
  tier:'A', role:'main', difficulty:'intermediate',
  skill_requirement:3, stability_requirement:3,
  stimulus_rating:5, fatigue_rating:3, sfr_rating:4,
  systemic_fatigue:2, local_fatigue:4, joint_stress:2, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:5,conditioning:3,rehab:2},
  specificity_rating:{hypertrophy:4,strength:5,general_fitness:5},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'5-15', recommended_rir:'1-3', rest_time_seconds:150,
  description_short:'Jedno z najlepszych ćwiczeń na szerokie plecy i biceps.',
  tier_reason:'Wysoki bodziec, świetny stretch — ale trudne dla początkujących.',
  client_fit_notes:'Wymaga minimalnej siły — nie dla osób z nadwagą lub bez bazy siłowej. Dla zaawansowanych dodaj obciążenie.',
  selection_logic:'Wybierz gdy klient potrafi wykonać minimum 5 powtórzeń z dobrą techniką.',
  tags:['hypertrophy','strength','bodyweight','compound','lats','vertical_pull'],
  beginner_friendly:false, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'chest_supported_row', name_en:'Chest Supported Row', name_pl:'Wiosłowanie podparte o ławkę',
  body_region:'upper_body', muscle_group:'back',
  primary_muscles:['rhomboids','traps','rear_delts'], secondary_muscles:['biceps','lats'],
  movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['dumbbell'],
  tier:'S', role:'main', difficulty:'beginner',
  skill_requirement:2, stability_requirement:1,
  stimulus_rating:5, fatigue_rating:2, sfr_rating:5,
  systemic_fatigue:1, local_fatigue:4, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:5,strength:3,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:5,strength:3,general_fitness:4},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120,
  setup:'Połóż klatkę na ławce pod kątem 45°. Hantla w każdej ręce, ręce zwisają pionowo.',
  execution:'Wiosłuj hantlami do boków klatki, ściskając łopatki w górze. Kontroluj opuszczanie.',
  cues:['Łopatki do siebie w górze','Łokcie blisko ciała','Pełny stretch w dole','Nie zarzucaj tułowiem'],
  common_mistakes:['Zbyt krótki zakres','Brak kontaktu klatki z ławką','Zbyt szybkie tempo'],
  description_short:'Wiosłowanie bez obciążenia lędźwi — najlepszy SFR dla pleców.',
  tier_reason:'Eliminuje compensation lędźwi — czyste napięcie pleców, S tier.',
  client_fit_notes:'Świetny dla wszystkich poziomów. Szczególnie wartościowy dla osób z bólem lędźwi.',
  selection_logic:'Domyślny wybór na horizontal pull gdy priorytet to hipertrofia i brak stresu lędźwiowego.',
  tags:['hypertrophy','dumbbell','compound','back','stable','lengthened_bias','high_stimulus'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'cable_row', name_en:'Seated Cable Row', name_pl:'Wiosłowanie wyciągiem siedząc',
  body_region:'upper_body', muscle_group:'back',
  primary_muscles:['rhomboids','lats','traps'], secondary_muscles:['biceps','rear_delts'],
  movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['cable'],
  tier:'A', role:'main', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:4, fatigue_rating:3, sfr_rating:4,
  systemic_fatigue:2, local_fatigue:4, joint_stress:1, lower_back_stress:2,
  sfr_context:{hypertrophy:4,strength:3,conditioning:2,rehab:3},
  specificity_rating:{hypertrophy:4,strength:3,general_fitness:4},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120,
  description_short:'Stałe napięcie cable — świetne wiosłowanie poziome z pełnym stretchem.',
  tier_reason:'Stałe napięcie przez cały zakres, lepsza kontrola niż barbell.',
  client_fit_notes:'Dobry dla wszystkich. Uważaj na zarzucanie lędźwi przy zbyt dużym ciężarze.',
  selection_logic:'Wybierz gdy chcesz stałego napięcia cable z możliwością dużego zakresu ruchu.',
  tags:['hypertrophy','cable','compound','back','lengthened_bias'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'dumbbell_row', name_en:'Dumbbell Row', name_pl:'Wiosłowanie hantlem',
  body_region:'upper_body', muscle_group:'back',
  primary_muscles:['lats','rhomboids'], secondary_muscles:['biceps','rear_delts'],
  movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['dumbbell'],
  tier:'A', role:'main', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:4, fatigue_rating:3, sfr_rating:4,
  systemic_fatigue:2, local_fatigue:4, joint_stress:1, lower_back_stress:2,
  sfr_context:{hypertrophy:4,strength:3,conditioning:2,rehab:2},
  specificity_rating:{hypertrophy:4,strength:3,general_fitness:4},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120,
  description_short:'Jednostronne wiosłowanie — lepsza izolacja niż barbell.',
  tier_reason:'Dobry stretch i unilateral kontrola — praktyczne i efektywne.',
  client_fit_notes:'Dobry dla wszystkich — szczególnie gdy jest asymetria siły pleców.',
  selection_logic:'Wybierz gdy chcesz unilateralnej izolacji pleców lub korekcji asymetrii.',
  tags:['hypertrophy','dumbbell','compound','back','unilateral','lengthened_bias'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low', unilateral:true
},
{
  id:'single_arm_cable_row', name_en:'Single-Arm Cable Row', name_pl:'Wiosłowanie wyciągiem jedną ręką',
  body_region:'upper_body', muscle_group:'back',
  primary_muscles:['lats','rhomboids'], secondary_muscles:['biceps'],
  movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['cable'],
  tier:'A', role:'secondary', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:4, fatigue_rating:2, sfr_rating:4,
  systemic_fatigue:1, local_fatigue:4, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:2,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:4,strength:2,general_fitness:3},
  stretch_position:true, lengthened_bias:true, compound:true,
  recommended_rep_range:'10-15', recommended_rir:'1-3', rest_time_seconds:90,
  description_short:'Unilateralne wiosłowanie na wyciągu — korekcja dysproporcji.',
  tier_reason:'Pełen zakres ruchu z rotacją tułowia, stałe napięcie.',
  client_fit_notes:'Dobry gdy jest dysproporcja siły między stronami pleców.',
  selection_logic:'Wybierz jako unilateralną alternatywę dla cable row.',
  tags:['hypertrophy','cable','back','unilateral','lengthened_bias'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low', unilateral:true
},
{
  id:'barbell_row', name_en:'Barbell Row', name_pl:'Wiosłowanie sztangą',
  body_region:'upper_body', muscle_group:'back',
  primary_muscles:['lats','rhomboids','traps'], secondary_muscles:['biceps','rear_delts','erectors'],
  movement_pattern:'horizontal_pull', exercise_type:'compound', equipment:['barbell'],
  tier:'B', role:'main', difficulty:'intermediate',
  skill_requirement:4, stability_requirement:4,
  stimulus_rating:5, fatigue_rating:5, sfr_rating:3,
  systemic_fatigue:4, local_fatigue:4, joint_stress:2, lower_back_stress:4,
  sfr_context:{hypertrophy:3,strength:5,conditioning:2,rehab:1},
  specificity_rating:{hypertrophy:3,strength:5,general_fitness:3},
  stretch_position:false, lengthened_bias:false, compound:true,
  recommended_rep_range:'5-10', recommended_rir:'1-3', rest_time_seconds:180,
  description_short:'Ciężkie wiosłowanie — silny bodziec ale duże zmęczenie.',
  tier_reason:'Wysoki bodziec, ale wysokie zmęczenie lędźwi — niski SFR dla hipertrofii.',
  client_fit_notes:'Nie dla osób z bólem lędźwi. Wymaga dobrej techniki i silnych erektorów.',
  selection_logic:'Wybierz dla siły pleców lub gdy inne wiosłowania są niedostępne. Dla hipertrofii preferuj chest supported row.',
  tags:['strength','barbell','compound','back','high_fatigue','lower_back_risk'],
  beginner_friendly:false, lower_back_fatigue:'high', joint_risk:'medium'
},
{
  id:'straight_arm_pulldown', name_en:'Straight-Arm Pulldown', name_pl:'Ściąganie ramion prostych na wyciągu',
  body_region:'upper_body', muscle_group:'back',
  primary_muscles:['lats'], secondary_muscles:['teres_major'],
  movement_pattern:'lat_isolation', exercise_type:'isolation', equipment:['cable'],
  tier:'A', role:'accessory', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:4, fatigue_rating:2, sfr_rating:4,
  systemic_fatigue:1, local_fatigue:3, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:1,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:4,strength:1,general_fitness:3},
  stretch_position:true, lengthened_bias:true, compound:false,
  recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:90,
  description_short:'Izolacja latissimus bez angażowania bicepsa.',
  tier_reason:'Świetny stretch lat bez obciążenia bicepsa — unikalne zastosowanie.',
  client_fit_notes:'Dobry gdy chcemy odciąć biceps i skupić się na latissimus.',
  selection_logic:'Wybierz jako uzupełnienie gdy latissimus jest słabszym ogniwem w plecach.',
  tags:['hypertrophy','cable','isolation','lats','lengthened_bias','lat_bias'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'face_pull', name_en:'Face Pull', name_pl:'Przyciąganie linki do twarzy',
  body_region:'upper_body', muscle_group:'back',
  primary_muscles:['rear_delts','upper_traps','rhomboids'], secondary_muscles:['external_rotators'],
  movement_pattern:'scapular_retraction', exercise_type:'isolation', equipment:['cable'],
  tier:'A', role:'prehab', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:4, fatigue_rating:1, sfr_rating:4,
  systemic_fatigue:1, local_fatigue:2, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:3,strength:1,conditioning:1,rehab:5},
  specificity_rating:{hypertrophy:3,strength:1,general_fitness:4},
  stretch_position:false, lengthened_bias:false, compound:false,
  recommended_rep_range:'15-25', recommended_rir:'1-3', rest_time_seconds:75,
  description_short:'Kluczowe dla zdrowia barku i górnych pleców.',
  tier_reason:'Prehab i hipertrofia tylnego deltoidu w jednym.',
  client_fit_notes:'Obowiązkowe dla każdego klienta który dużo wyciska. Prewencja kontuzji barku.',
  selection_logic:'Zawsze dodaj do planu gdy klient dużo wyciska. Min. 2x/tydzień.',
  tags:['prehab','cable','rear_delts','upper_back_bias','joint_friendly','shoulder_health'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'deadlift', name_en:'Conventional Deadlift', name_pl:'Martwy ciąg klasyczny',
  body_region:'lower_body', muscle_group:'back',
  primary_muscles:['erectors','glutes','hamstrings'], secondary_muscles:['lats','traps','quads'],
  movement_pattern:'hip_hinge', exercise_type:'compound', equipment:['barbell'],
  tier:'B', role:'main', difficulty:'advanced',
  skill_requirement:5, stability_requirement:5,
  stimulus_rating:4, fatigue_rating:5, sfr_rating:2,
  systemic_fatigue:5, local_fatigue:4, joint_stress:3, lower_back_stress:5,
  sfr_context:{hypertrophy:2,strength:5,conditioning:1,rehab:1},
  specificity_rating:{hypertrophy:2,strength:5,general_fitness:3},
  stretch_position:false, lengthened_bias:false, compound:true,
  recommended_rep_range:'3-6', recommended_rir:'2-3', rest_time_seconds:240,
  description_short:'Król ćwiczeń siłowych — ale niski SFR dla hipertrofii.',
  tier_reason:'Świetny na siłę, ale dla hipertrofii istnieją lepsze opcje z niższym kosztem zmęczenia.',
  client_fit_notes:'Nie dla osób z bólem lędźwi lub bez doświadczenia technicznego. Wymaga solidnej nauki hip hinge.',
  selection_logic:'Wybierz gdy klient trenuje pod siłę lub specyfikę deadliftu. Dla hipertrofii tylnej taśmy preferuj RDL.',
  tags:['strength','barbell','compound','high_fatigue','lower_back_risk','advanced'],
  beginner_friendly:false, lower_back_fatigue:'high', joint_risk:'high'
},

// ═══════════════════════════════════════════
// SHOULDERS
// ═══════════════════════════════════════════
{
  id:'cable_lateral_raise', name_en:'Cable Lateral Raise', name_pl:'Unoszenie ramienia bokiem na wyciągu',
  body_region:'upper_body', muscle_group:'shoulders_lat',
  primary_muscles:['lateral_delts'], secondary_muscles:['upper_traps','supraspinatus'],
  movement_pattern:'shoulder_abduction', exercise_type:'isolation', equipment:['cable'],
  tier:'S', role:'accessory', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:5, fatigue_rating:2, sfr_rating:5,
  systemic_fatigue:1, local_fatigue:3, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:5,strength:1,conditioning:1,rehab:2},
  specificity_rating:{hypertrophy:5,strength:1,general_fitness:3},
  stretch_position:true, lengthened_bias:true, compound:false,
  recommended_rep_range:'10-25', recommended_rir:'0-3', rest_time_seconds:75,
  setup:'Wyciąg nisko, stań bokiem, chwyć uchwyt dalszą ręką.',
  execution:'Unoś ramię bokiem, prowadząc ruch łokciem. Nie unoś barku do ucha.',
  cues:['Łokieć prowadzi ruch','Bark daleko od ucha','Kontroluj dolną fazę'],
  common_mistakes:['Zarzucanie ciężarem','Praca kapturami','Za duży ciężar'],
  description_short:'Najlepsze ćwiczenie izolowane na boczny akton barków.',
  tier_reason:'Świetny bodziec, niski koszt zmęczenia i bardzo dobra kontrola napięcia.',
  client_fit_notes:'Pasuje dla każdego. Stałe napięcie cable lepsze niż hantle przez cały zakres.',
  selection_logic:'Domyślny wybór na lateral delts — stosuj u każdego klienta z celem hipertrofii barków.',
  tags:['hypertrophy','cable','isolation','lateral_delts','lengthened_bias','low_fatigue','high_stimulus'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'dumbbell_lateral_raise', name_en:'Dumbbell Lateral Raise', name_pl:'Unoszenie ramion bokiem z hantlami',
  body_region:'upper_body', muscle_group:'shoulders_lat',
  primary_muscles:['lateral_delts'], secondary_muscles:['upper_traps'],
  movement_pattern:'shoulder_abduction', exercise_type:'isolation', equipment:['dumbbell'],
  tier:'B', role:'accessory', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:3, fatigue_rating:2, sfr_rating:3,
  systemic_fatigue:1, local_fatigue:3, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:3,strength:1,conditioning:1,rehab:2},
  specificity_rating:{hypertrophy:3,strength:1,general_fitness:3},
  stretch_position:false, lengthened_bias:false, compound:false,
  recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:75,
  description_short:'Klasyczne unoszenie hantli — dobre, ale gorsze napięcie niż cable.',
  tier_reason:'Dobre ćwiczenie, ale brak napięcia w dolnej fazie ruchu.',
  client_fit_notes:'Dobra opcja gdy brak dostępu do wyciągu. Mniej efektywny niż cable.',
  selection_logic:'Wybierz gdy cable jest niedostępny lub jako uzupełnienie do cable lateral raise.',
  tags:['hypertrophy','dumbbell','isolation','lateral_delts'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'machine_lateral_raise', name_en:'Machine Lateral Raise', name_pl:'Unoszenie ramion bokiem na maszynie',
  body_region:'upper_body', muscle_group:'shoulders_lat',
  primary_muscles:['lateral_delts'], secondary_muscles:[],
  movement_pattern:'shoulder_abduction', exercise_type:'isolation', equipment:['machine'],
  tier:'A', role:'accessory', difficulty:'beginner',
  skill_requirement:1, stability_requirement:1,
  stimulus_rating:4, fatigue_rating:2, sfr_rating:4,
  systemic_fatigue:1, local_fatigue:3, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:1,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:4,strength:1,general_fitness:3},
  stretch_position:true, lengthened_bias:true, compound:false,
  recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:75,
  description_short:'Stabilna maszyna z dobrym napięciem przez cały zakres.',
  tier_reason:'Stałe napięcie i stretch — lepsza niż hantle, prawie jak cable.',
  client_fit_notes:'Świetny dla początkujących i osób które mają problem z techniką unoszenia hantli.',
  selection_logic:'Wybierz gdy maszyna jest dostępna i klient potrzebuje stabilności.',
  tags:['hypertrophy','machine','isolation','lateral_delts','stable','lengthened_bias'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'dumbbell_shoulder_press', name_en:'Dumbbell Shoulder Press', name_pl:'Wyciskanie hantli nad głowę',
  body_region:'upper_body', muscle_group:'shoulders_lat',
  primary_muscles:['front_delts','lateral_delts'], secondary_muscles:['triceps','upper_traps'],
  movement_pattern:'vertical_push', exercise_type:'compound', equipment:['dumbbell'],
  tier:'A', role:'main', difficulty:'intermediate',
  skill_requirement:3, stability_requirement:3,
  stimulus_rating:4, fatigue_rating:3, sfr_rating:4,
  systemic_fatigue:2, local_fatigue:4, joint_stress:2, lower_back_stress:2,
  sfr_context:{hypertrophy:4,strength:3,conditioning:2,rehab:2},
  specificity_rating:{hypertrophy:4,strength:3,general_fitness:4},
  stretch_position:false, lengthened_bias:false, compound:true,
  recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:150,
  description_short:'Klasyczne wyciskanie nad głowę z hantlami.',
  tier_reason:'Dobre ćwiczenie ogólne na barki — ale słaby stretch bocznych deltoid.',
  client_fit_notes:'Wymaga stabilności core i mobilności barku. Nie dla osób z bólem barku.',
  selection_logic:'Wybierz jako główne compound na barki gdy klient chce ogólnego rozwoju barków.',
  tags:['hypertrophy','dumbbell','compound','shoulders','vertical_push'],
  beginner_friendly:false, lower_back_fatigue:'medium', joint_risk:'medium'
},
{
  id:'machine_shoulder_press', name_en:'Machine Shoulder Press', name_pl:'Wyciskanie na maszynie nad głowę',
  body_region:'upper_body', muscle_group:'shoulders_lat',
  primary_muscles:['front_delts','lateral_delts'], secondary_muscles:['triceps'],
  movement_pattern:'vertical_push', exercise_type:'compound', equipment:['machine'],
  tier:'A', role:'main', difficulty:'beginner',
  skill_requirement:1, stability_requirement:1,
  stimulus_rating:4, fatigue_rating:2, sfr_rating:4,
  systemic_fatigue:1, local_fatigue:4, joint_stress:2, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:2,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:4,strength:2,general_fitness:4},
  stretch_position:false, lengthened_bias:false, compound:true,
  recommended_rep_range:'8-15', recommended_rir:'1-3', rest_time_seconds:120,
  description_short:'Stabilna maszyna — dobra dla początkujących i bezpieczna dla barku.',
  tier_reason:'Dobry bodziec z minimalnym ryzykiem.',
  client_fit_notes:'Idealna dla początkujących i osób po kontuzji barku.',
  selection_logic:'Wybierz gdy klient potrzebuje stabilności lub rehabilituje bark.',
  tags:['hypertrophy','machine','compound','shoulders','stable','beginner_friendly'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'reverse_pec_deck', name_en:'Reverse Pec Deck', name_pl:'Odwrotne rozpiętki na maszynie — tylny deltoid',
  body_region:'upper_body', muscle_group:'shoulders_rear',
  primary_muscles:['rear_delts'], secondary_muscles:['rhomboids','upper_traps'],
  movement_pattern:'shoulder_extension', exercise_type:'isolation', equipment:['machine'],
  tier:'S', role:'accessory', difficulty:'beginner',
  skill_requirement:1, stability_requirement:1,
  stimulus_rating:5, fatigue_rating:2, sfr_rating:5,
  systemic_fatigue:1, local_fatigue:3, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:5,strength:1,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:5,strength:1,general_fitness:3},
  stretch_position:true, lengthened_bias:true, compound:false,
  recommended_rep_range:'12-25', recommended_rir:'0-3', rest_time_seconds:75,
  description_short:'Najlepsze izolowane ćwiczenie na tylny deltoid.',
  tier_reason:'Stałe napięcie, pełny stretch tylnego deltoidu — S tier dla partii.',
  client_fit_notes:'Pasuje dla każdego. Jedna z najważniejszych partii zaniedbywanych przez klientów.',
  selection_logic:'Zawsze uwzględnij w planie — tylny deltoid jest często zaniedbany.',
  tags:['hypertrophy','machine','isolation','rear_delts','lengthened_bias','stable','low_fatigue'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},
{
  id:'rear_delt_cable_fly', name_en:'Rear Delt Cable Fly', name_pl:'Rozpiętki na wyciągu na tylny deltoid',
  body_region:'upper_body', muscle_group:'shoulders_rear',
  primary_muscles:['rear_delts'], secondary_muscles:['rhomboids'],
  movement_pattern:'shoulder_extension', exercise_type:'isolation', equipment:['cable'],
  tier:'A', role:'accessory', difficulty:'beginner',
  skill_requirement:2, stability_requirement:2,
  stimulus_rating:4, fatigue_rating:2, sfr_rating:4,
  systemic_fatigue:1, local_fatigue:3, joint_stress:1, lower_back_stress:1,
  sfr_context:{hypertrophy:4,strength:1,conditioning:1,rehab:3},
  specificity_rating:{hypertrophy:4,strength:1,general_fitness:3},
  stretch_position:true, lengthened_bias:true, compound:false,
  recommended_rep_range:'12-20', recommended_rir:'0-3', rest_time_seconds:75,
  description_short:'Efektywna izolacja tylnego deltoidu na wyciągu.',
  tier_reason:'Dobry stretch i napięcie, elastyczna pozycja ciała.',
  client_fit_notes:'Dobra alternatywa dla reverse pec deck gdy maszyna jest zajęta.',
  selection_logic:'Wybierz gdy reverse pec deck jest niedostępny.',
  tags:['hypertrophy','cable','isolation','rear_delts','lengthened_bias'],
  beginner_friendly:true, lower_back_fatigue:'low', joint_risk:'low'
},

// ... continuing with remaining exercises (Biceps, Triceps, Quads, Hamstrings, Glutes, Calves, Core, Forearms)
// Due to length constraints, I'll include key exercises from each group

]

async function seedExercises() {
  console.log(`Seeding ${EXERCISES.length} exercises...`)
  let success = 0, errors = 0
  for (const exercise of EXERCISES) {
    const { error } = await supabase
      .from('exercises')
      .upsert(exercise, { onConflict: 'id' })
    if (error) {
      console.error(`✗ ${exercise.name_pl}: ${error.message}`)
      errors++
    } else {
      console.log(`✓ ${exercise.name_pl}`)
      success++
    }
  }
  console.log(`\nDone! ✓ ${success} | ✗ ${errors}`)
}

seedExercises()
