export const DAILY_TIPS = [

// ─── NAWODNIENIE (12) ──────────────────────────────────────────────────────
{ id:'hydration_001', category:'hydration', title:'Zacznij dzień od wody', content:'Po nocy organizm jest lekko odwodniony, nawet jeśli nie czujesz pragnienia. Szklanka wody rano pomaga wrócić do normalnego poziomu nawodnienia i może ułatwić kontrolę apetytu przez resztę dnia.', sourceLabel:'Sports Nutrition Guidelines', level:'beginner', goal:['fat_loss','muscle_gain','health'], tags:['water','morning','habit'] },
{ id:'hydration_002', category:'hydration', title:'Kawa to nie wróg nawodnienia', content:'Kawa działa lekko moczopędnie, ale u osób przyzwyczajonych nadal liczy się częściowo do podaży płynów. Problem zaczyna się wtedy, gdy kawa całkowicie zastępuje wodę przez większość dnia.', sourceLabel:'General Nutrition Evidence', level:'beginner', goal:['health','fat_loss'], tags:['coffee','water','hydration'] },
{ id:'hydration_003', category:'hydration', title:'Ciemny mocz to sygnał', content:'Kolor moczu to prosty wskaźnik nawodnienia. Słomkowy żółty to cel. Ciemny, intensywny kolor oznacza, że powinieneś sięgnąć po szklankę wody zanim zasiądziesz do kolejnego zadania.', sourceLabel:'Sports Medicine Guidelines', level:'beginner', goal:['health'], tags:['hydration','indicator','practical'] },
{ id:'hydration_004', category:'hydration', title:'Nawodnij się przed treningiem', content:'Wejście na trening odwodnionym to szybka droga do gorszej wydajności i szybszego zmęczenia. Nawet 1–2% odwodnienia może zmniejszyć siłę i koncentrację. Szklanka wody 30 minut przed treningiem to minimum.', sourceLabel:'ACSM Hydration Guidelines', level:'beginner', goal:['muscle_gain','fat_loss'], tags:['training','hydration','performance'] },
{ id:'hydration_005', category:'hydration', title:'Elektrolity przy dużej aktywności', content:'Przy intensywnym treningu lub dużej ilości kroków w upał tracisz nie tylko wodę, ale też elektrolity. Szczypka soli do wody lub naturalny izotonik mogą pomóc przy bardzo aktywnych dniach.', sourceLabel:'Sports Nutrition Practice', level:'intermediate', goal:['health','muscle_gain'], tags:['electrolytes','sweat','performance'] },
{ id:'hydration_006', category:'hydration', title:'2 litry to mit, nie reguła', content:'Zapotrzebowanie na wodę zależy od masy ciała, aktywności i temperatury. Zamiast liczyć litry, obserwuj kolor moczu i słuchaj pragnienia po rozgrzewce organizmu. Różne osoby potrzebują różnych ilości.', sourceLabel:'General Nutrition Evidence', level:'beginner', goal:['health'], tags:['water','myths','practical'] },
{ id:'hydration_007', category:'hydration', title:'Woda przed posiłkiem', content:'Szklanka wody 15–20 minut przed posiłkiem może pomóc w sytości, szczególnie w redukcji. To prosta sztuczka, która nic nie kosztuje i może zmniejszyć tendencję do przejadania się.', sourceLabel:'Lyle McDonald / Fat Loss Principles', level:'beginner', goal:['fat_loss'], tags:['satiety','water','fat_loss'] },
{ id:'hydration_008', category:'hydration', title:'Herbata i napary liczą się', content:'Herbata, napary ziołowe i kawa (bez cukru) liczą się do dobowego bilansu płynów. Nie musisz pić wyłącznie wody, żeby być dobrze nawodnionym. Variety pomaga w regularności.', sourceLabel:'General Nutrition Evidence', level:'beginner', goal:['health'], tags:['tea','hydration','variety'] },
{ id:'hydration_009', category:'hydration', title:'Nawodnienie wpływa na głód', content:'Czasem to co czujesz jako głód to odwodnienie. Zanim sięgniesz po przekąskę, wypij szklankę wody i poczekaj 10 minut. To szczególnie przydatne w redukcji, gdy chcesz kontrolować kalorie.', sourceLabel:'Lyle McDonald / Fat Loss Principles', level:'beginner', goal:['fat_loss'], tags:['hunger','water','fat_loss'] },
{ id:'hydration_010', category:'hydration', title:'Alkohol odwadnia podwójnie', content:'Alkohol hamuje hormon antydiuretyczny, przez co tracisz więcej wody niż normalnie. Dlatego kac to po części odwodnienie. Szklanka wody między drinkami i po powrocie do domu naprawdę pomaga.', sourceLabel:'General Nutrition Evidence', level:'beginner', goal:['health'], tags:['alcohol','hydration','recovery'] },
{ id:'hydration_011', category:'hydration', title:'Nawodnienie a jakość snu', content:'Picie dużo płynów tuż przed snem może zaburzać sen przez nocne wizyty w toalecie. Większość płynów uzupełniaj rano i po południu, ograniczając je na 1–2 godziny przed snem.', sourceLabel:'Huberman Lab / Sleep Principles', level:'beginner', goal:['health','muscle_gain'], tags:['sleep','hydration','timing'] },
{ id:'hydration_012', category:'hydration', title:'Woda kokosowa jako naturalny izotonik', content:'Woda kokosowa zawiera potas i elektrolity w naturalnej formie. To dobra opcja po treningu lub w gorące dni, choć ma kalorie, więc w redukcji traktuj ją jako część bilansu.', sourceLabel:'Sports Nutrition Practice', level:'intermediate', goal:['health','muscle_gain'], tags:['coconut','electrolytes','natural'] },

// ─── SEN (15) ──────────────────────────────────────────────────────────────
{ id:'sleep_001', category:'sleep', title:'Stała godzina pobudki wygrywa', content:'Najłatwiejszym sposobem stabilizacji rytmu dobowego jest regularna godzina wstawania. Nawet jeśli sen nie był idealny, stała pobudka pomaga organizmowi szybciej wrócić do rytmu.', sourceLabel:'Huberman Lab / Circadian Rhythm', level:'beginner', goal:['health','fat_loss','muscle_gain'], tags:['sleep','circadian','routine'] },
{ id:'sleep_002', category:'sleep', title:'Sen to legalny booster progresu', content:'Zbyt krótki sen pogarsza regenerację, apetyt, motywację i jakość treningu. Jeśli śpisz słabo przez kilka dni, nie oczekuj od ciała, że będzie działać jak maszyna premium. Sen to nie lenistwo, to narzędzie.', sourceLabel:'Peter Attia / Recovery Principles', level:'beginner', goal:['fat_loss','muscle_gain','health'], tags:['sleep','recovery','performance'] },
{ id:'sleep_003', category:'sleep', title:'Światło rano, ciemność wieczorem', content:'Ekspozycja na naturalne światło rano synchronizuje zegar biologiczny. Wieczorem przyciemnij ekrany i oświetlenie. Ten prosty schemat może znacznie poprawić jakość snu bez suplementów.', sourceLabel:'Huberman Lab / Circadian Rhythm', level:'beginner', goal:['health'], tags:['light','circadian','sleep_quality'] },
{ id:'sleep_004', category:'sleep', title:'Temperatura sypialni ma znaczenie', content:'Ciało potrzebuje obniżenia temperatury rdzenia, żeby zasnąć i utrzymać głęboki sen. Chłodniejsza sypialnia (ok. 18–19°C) sprzyja lepszej jakości snu niż ciepła.', sourceLabel:'Matthew Walker / Why We Sleep', level:'beginner', goal:['health','muscle_gain'], tags:['temperature','sleep_environment','recovery'] },
{ id:'sleep_005', category:'sleep', title:'Kofeina ma długie życie', content:'Czas półtrwania kofeiny to ok. 5–6 godzin. Kawa o 15:00 oznacza, że o 21:00 połowa kofeiny nadal krąży w Twoim organizmie. Jeśli masz problem ze snem, przesuń ostatnią kawę na przed południe.', sourceLabel:'Huberman Lab / Caffeine & Sleep', level:'beginner', goal:['health','fat_loss'], tags:['caffeine','coffee','sleep'] },
{ id:'sleep_006', category:'sleep', title:'Niedobór snu zwiększa głód', content:'Krótki sen podnosi poziom greliny (hormon głodu) i obniża leptynę (sygnał sytości). Osoby śpiące za krótko często mają silniejsze łaknienie i trudniej im utrzymać deficyt kaloryczny.', sourceLabel:'Matthew Walker / Why We Sleep', level:'intermediate', goal:['fat_loss','health'], tags:['hunger','hormones','fat_loss'] },
{ id:'sleep_007', category:'sleep', title:'Alkohol niszczy jakość snu', content:'Alkohol może ułatwiać zasypianie, ale głęboko zaburza fazy REM i głębokiego snu. Efekt to gorszy sen pomimo podobnej długości. Szczególnie uderza to w regenerację mięśniową.', sourceLabel:'Matthew Walker / Why We Sleep', level:'beginner', goal:['health','muscle_gain'], tags:['alcohol','rem','recovery'] },
{ id:'sleep_008', category:'sleep', title:'Drzemka to nie wstyd', content:'20–30 minutowa drzemka po południu może poprawić czujność i nastrój bez wpływu na sen nocny. Dłuższa drzemka lub zbyt późna może jednak utrudnić zasypianie.', sourceLabel:'Huberman Lab / Napping', level:'beginner', goal:['health','performance'], tags:['nap','recovery','energy'] },
{ id:'sleep_009', category:'sleep', title:'Magnezu a sen', content:'Magnez biorący udział w regulacji układu nerwowego może wspierać jakość snu. Formy glicynian lub taurat są dobrze przyswajalne. To jeden z nielicznych suplementów z realnym wsparciem w literaturze.', sourceLabel:'Examine.com / Magnesium', level:'intermediate', goal:['health','muscle_gain'], tags:['magnesium','supplements','sleep'] },
{ id:'sleep_010', category:'sleep', title:'Sen przed północą jest cenniejszy', content:'Sen przed północą zawiera proporcjonalnie więcej snu głębokiego (NREM), który odpowiada za regenerację fizyczną. Sen po północy ma więcej REM, który służy pamięci i emocjom. Obie fazy są ważne.', sourceLabel:'Matthew Walker / Why We Sleep', level:'intermediate', goal:['muscle_gain','health'], tags:['deep_sleep','rem','timing'] },
{ id:'sleep_011', category:'sleep', title:'Trening wieczorem to nie zawsze problem', content:'Trening wieczorny może podnosić temperaturę ciała i kortyzo, co utrudnia zasypianie u niektórych. Ale badania pokazują, że efekt jest indywidualny. Obserwuj swój organizm i dostosuj godzinę.', sourceLabel:'Sports Science Research', level:'intermediate', goal:['muscle_gain','fat_loss'], tags:['evening_training','sleep','individual'] },
{ id:'sleep_012', category:'sleep', title:'Rutyna wieczorna działa', content:'Stały rytuał przed snem (np. prysznic, czytanie, przyciemnienie) sygnalizuje mózgowi, że pora na odpoczynek. Prostota wygrywa — nie potrzebujesz 20-krokowego rytuału, wystarczy konsekwencja.', sourceLabel:'Huberman Lab / Sleep Toolkit', level:'beginner', goal:['health'], tags:['routine','sleep_hygiene','habit'] },
{ id:'sleep_013', category:'sleep', title:'Długi sen w weekend nie nadrabia', content:'Próba "nadrobienia" snu w weekend częściowo działa, ale nie w pełni. Chroniczny niedobór snu ma skumulowany efekt, którego dwie noce nie naprawią. Regularność jest ważniejsza niż długie weekendowe spanie.', sourceLabel:'Matthew Walker / Sleep Science', level:'intermediate', goal:['health','muscle_gain'], tags:['sleep_debt','weekend','regularity'] },
{ id:'sleep_014', category:'sleep', title:'Stres a sen to błędne koło', content:'Stres utrudnia zasypianie, a brak snu podnosi poziom kortyzolu. To błędne koło, które można przerwać przez techniki relaksacyjne, regularną aktywność i ograniczenie ekranów wieczorem.', sourceLabel:'Peter Attia / Stress & Recovery', level:'intermediate', goal:['health'], tags:['stress','cortisol','sleep'] },
{ id:'sleep_015', category:'sleep', title:'7–9 godzin to cel dla dorosłych', content:'Większość dorosłych potrzebuje 7–9 godzin snu. Niektórzy funkcjonują na 6, ale są to genetyczne wyjątki stanowiące mniej niż 3% populacji. Jeśli myślisz, że jesteś jednym z nich — możliwe, że po prostu nie wiesz jak dobrze się czujesz po porządnym śnie.', sourceLabel:'Matthew Walker / Why We Sleep', level:'beginner', goal:['health','muscle_gain','fat_loss'], tags:['sleep_duration','myths','basics'] },

// ─── ŻYWIENIE (20) ─────────────────────────────────────────────────────────
{ id:'nutrition_001', category:'nutrition', title:'Białko na śniadanie ułatwia dzień', content:'Porcja białka rano może pomóc w sytości i łatwiejszym dobiciu celu białkowego w ciągu dnia. Nie musi to być magiczne śniadanie mistrzów — po prostu solidna porcja białka robi robotę.', sourceLabel:'Eric Helms / Muscle & Strength Nutrition', level:'beginner', goal:['fat_loss','muscle_gain','recomp'], tags:['protein','breakfast','satiety'] },
{ id:'nutrition_002', category:'nutrition', title:'Nie panikuj po jednym skoku wagi', content:'Jednodniowy wzrost masy zwykle wynika z wody, soli, węglowodanów, stresu lub trawienia. Decyzje dietetyczne podejmuj na podstawie trendu z 7 dni, nie jednej porannej liczby.', sourceLabel:'Lyle McDonald / Fat Loss Principles', level:'beginner', goal:['fat_loss','recomp'], tags:['weight_trend','fat_loss','water'] },
{ id:'nutrition_003', category:'nutrition', title:'Białko to najsycący makroskładnik', content:'Białko daje największe uczucie sytości ze wszystkich makroskładników. Dieta wysokobiałkowa w redukcji pomaga kontrolować apetyt i chronić masę mięśniową jednocześnie.', sourceLabel:'Eric Helms / Nutrition Principles', level:'beginner', goal:['fat_loss','muscle_gain'], tags:['protein','satiety','fat_loss'] },
{ id:'nutrition_004', category:'nutrition', title:'Węglowodany nie są wrogiem', content:'Węglowodany same w sobie nie powodują tycia. Nadwyżka kaloryczna powoduje tycie, niezależnie od źródła. Węgle to paliwo dla treningu i mózgu — ważne jest ich ilość i timing, nie sam fakt jedzenia.', sourceLabel:'Alan Aragon / Nutrition Evidence', level:'beginner', goal:['muscle_gain','recomp','health'], tags:['carbs','myths','energy'] },
{ id:'nutrition_005', category:'nutrition', title:'Tłuszcz jest konieczny dla zdrowia', content:'Tłuszcze są niezbędne do produkcji hormonów, przyswajania witamin A/D/E/K i pracy układu nerwowego. Minimum 0.7–0.8 g/kg masy ciała dziennie to poziom, poniżej którego zaczyna się problem.', sourceLabel:'Lyle McDonald / Dietary Fat', level:'intermediate', goal:['health','fat_loss','muscle_gain'], tags:['fat','hormones','minimum'] },
{ id:'nutrition_006', category:'nutrition', title:'Objętość jedzenia ma znaczenie w redukcji', content:'Warzywa, zupy, produkty bogate w wodę i błonnik pozwalają jeść dużo objętościowo przy małej ilości kalorii. To strategia, która pomaga czuć się syto w deficycie bez ciągłego walczenia z głodem.', sourceLabel:'Lyle McDonald / Flexible Dieting', level:'beginner', goal:['fat_loss'], tags:['volume_eating','satiety','vegetables'] },
{ id:'nutrition_007', category:'nutrition', title:'Jakość snu a jedzenie to pętla', content:'Niedobór snu pogarsza wybory żywieniowe i zwiększa chęć na słodkie i tłuste. Z kolei ciężkie jedzenie wieczorem może zaburzać sen. Te dwa elementy mocno się wzajemnie wpływają.', sourceLabel:'Matthew Walker / Sleep & Nutrition', level:'intermediate', goal:['fat_loss','health'], tags:['sleep','food_choices','connection'] },
{ id:'nutrition_008', category:'nutrition', title:'Jedno potknięcie nie niszczy diety', content:'Jedna kolacja poza planem nie niszczy tygodniowego deficytu. Matematyka kalorii działa na poziomie tygodnia, nie jednego posiłku. Problem pojawia się, gdy jedno potknięcie uruchamia myślenie "i tak już wszystko zniszczyłem".', sourceLabel:'Lyle McDonald / Flexible Dieting', level:'beginner', goal:['fat_loss','recomp'], tags:['flexibility','adherence','all_or_nothing'] },
{ id:'nutrition_009', category:'nutrition', title:'Błonnik wspiera sytość i trawienie', content:'Błonnik spowalnia trawienie, pomaga w sytości i wspiera mikrobiom jelitowy. Warzywa, owoce, rośliny strączkowe i pełnoziarniste produkty to naturalne źródła, które warto mieć w każdym posiłku.', sourceLabel:'General Nutrition Evidence', level:'beginner', goal:['health','fat_loss'], tags:['fiber','satiety','digestion'] },
{ id:'nutrition_010', category:'nutrition', title:'Posiłki okołotreningowe mają sens', content:'Białko i węglowodany przed lub po treningu wspierają syntezę białek mięśniowych. Nie musisz być perfekcyjny co do minuty, ale posiłek z białkiem w oknie 2 godzin po treningu to dobra praktyka.', sourceLabel:'Eric Helms / Nutrient Timing', level:'intermediate', goal:['muscle_gain','recomp'], tags:['timing','post_workout','protein'] },
{ id:'nutrition_011', category:'nutrition', title:'Nie jedz na autopilocie', content:'Jedzenie przy ekranie, podczas pracy lub w biegu często prowadzi do zjedzenia więcej niż potrzebujesz, bo nie rejestrujesz sygnałów sytości. Kilka posiłków w skupieniu tygodniowo może zrobić dużą różnicę.', sourceLabel:'General Nutrition Practice', level:'beginner', goal:['fat_loss','health'], tags:['mindful_eating','habits','awareness'] },
{ id:'nutrition_012', category:'nutrition', title:'Cukier a tłuszcz — co jest winne?', content:'Żaden makroskładnik nie jest "winny" sam w sobie. Otyłość to wynik nadwyżki kalorycznej, nie jednego składnika. Demonizowanie jednego produktu lub grupy to uproszczenie, które prowadzi do restrykcyjnych cykli.', sourceLabel:'Alan Aragon / Nutrition Evidence', level:'intermediate', goal:['health','fat_loss'], tags:['sugar','fat','myths'] },
{ id:'nutrition_013', category:'nutrition', title:'Rozkład kalorii w ciągu dnia', content:'Równomierne rozłożenie kalorii i białka na 3–5 posiłków dziennie wspiera syntezę białek mięśniowych lepiej niż jedno duże danie. W praktyce — nie pomijaj śniadania i nie przesuwaj wszystkiego na wieczór.', sourceLabel:'Eric Helms / Meal Distribution', level:'intermediate', goal:['muscle_gain','recomp'], tags:['meal_frequency','protein_distribution','mps'] },
{ id:'nutrition_014', category:'nutrition', title:'Etykiety kłamią o kaloriach', content:'Prawo zezwala na błąd do 20% na etykietach produktów. Dlatego ważenie jedzenia daje dokładniejszy obraz niż liczenie "porcji z opakowania". Nie musisz obsesyjnie ważyć wszystkiego, ale warto wiedzieć, że etykiety to przybliżenia.', sourceLabel:'General Nutrition Evidence', level:'intermediate', goal:['fat_loss'], tags:['labels','accuracy','tracking'] },
{ id:'nutrition_015', category:'nutrition', title:'Przetworzone jedzenie a sytość', content:'Wysoko przetworzone produkty są często zaprojektowane tak, żeby być smaczne i wciągające, ale nie sycące. Całościowe produkty z błonnikiem, białkiem i wodą dają lepszą sytość przy mniejszej ilości kalorii.', sourceLabel:'General Nutrition Evidence', level:'beginner', goal:['fat_loss','health'], tags:['processed_food','satiety','whole_foods'] },
{ id:'nutrition_016', category:'nutrition', title:'Głód to nie awaria', content:'Lekki głód w redukcji jest normalny i nie oznacza, że coś jest nie tak. Problem pojawia się przy ekstremalnym głodzie lub ciągłym wyczerpaniu. Monitoring sygnałów głodu to umiejętność, którą warto rozwijać.', sourceLabel:'Eric Helms / Flexible Dieting', level:'beginner', goal:['fat_loss'], tags:['hunger','fat_loss','normal'] },
{ id:'nutrition_017', category:'nutrition', title:'Omega-3 to jeden z fundamentów', content:'Kwasy omega-3 (szczególnie EPA i DHA) mają silne wsparcie naukowe dla zdrowia sercowo-naczyniowego, redukcji stanu zapalnego i funkcji mózgu. Tłuste ryby 2–3 razy w tygodniu lub suplementacja to rozsądna strategia.', sourceLabel:'ISSN / Omega-3 Position', level:'intermediate', goal:['health','muscle_gain'], tags:['omega3','fish','inflammation'] },
{ id:'nutrition_018', category:'nutrition', title:'Nawodnienie a głód — znowu', content:'Wiele osób myli sygnał pragnienia z głodem, szczególnie gdy rzadko piją wodę. Szklanka wody przed oceną głodu to prosty test, który może zmniejszyć bezpotrzebne podjadanie.', sourceLabel:'General Nutrition Practice', level:'beginner', goal:['fat_loss'], tags:['thirst','hunger','water'] },
{ id:'nutrition_019', category:'nutrition', title:'Indeks glikemiczny — ważny, ale nie najważniejszy', content:'Indeks glikemiczny produktu zmienia się zależnie od porcji, kombinacji z innymi składnikami i sposobu przygotowania. Dla większości osób ładunek glikemiczny całego posiłku ma większe znaczenie niż IG pojedynczego produktu.', sourceLabel:'General Nutrition Evidence', level:'advanced', goal:['health','fat_loss'], tags:['glycemic_index','carbs','practical'] },
{ id:'nutrition_020', category:'nutrition', title:'Jedzenie dla przyjemności to też zdrowie', content:'Relacja z jedzeniem jest częścią zdrowia. Eliminowanie wszystkich "przyjemnych" produktów może prowadzić do obsesji i cykli restrykcja-objadanie. Włączenie ulubionych jedzeni w rozsądnych ilościach jest strategią, nie porażką.', sourceLabel:'Alan Aragon / Flexible Dieting', level:'beginner', goal:['health','fat_loss'], tags:['enjoyment','flexibility','mental_health'] },

// ─── TRENING (20) ──────────────────────────────────────────────────────────
{ id:'training_001', category:'training', title:'Progresja to nie tylko ciężar', content:'Progressive overload może oznaczać większy ciężar, więcej powtórzeń, lepszą technikę albo większą kontrolę ruchu. Jeśli technika się sypie przy dokładaniu ciężaru, to nie jest progresja, to negocjacja z kontuzją.', sourceLabel:'Mike Israetel / Hypertrophy Principles', level:'intermediate', goal:['muscle_gain','recomp'], tags:['progressive_overload','technique','hypertrophy'] },
{ id:'training_002', category:'training', title:'RIR ma sens tylko przy szczerości', content:'RIR oznacza liczbę powtórzeń w zapasie. Jeśli wpisujesz RIR 2, ale realnie walczysz o życie na ostatnim powtórzeniu, system dostaje złe dane i podejmie gorszą decyzję. Szczerość w logowaniu to część treningu.', sourceLabel:'Eric Helms / RIR Autoregulation', level:'beginner', goal:['muscle_gain','strength'], tags:['rir','autoregulation','logging'] },
{ id:'training_003', category:'training', title:'Rozgrzewka to nie czas do stracenia', content:'Dobra rozgrzewka aktywuje mięśnie, podnosi temperaturę ciała i przygotowuje stawy. 5–10 minut celowanej rozgrzewki zmniejsza ryzyko kontuzji i często poprawia jakość pierwszych serii roboczych.', sourceLabel:'Sports Science Practice', level:'beginner', goal:['muscle_gain','health'], tags:['warmup','injury_prevention','performance'] },
{ id:'training_004', category:'training', title:'Objętość tygodniowa, nie jedna sesja', content:'Hipertrofia zależy od łącznej objętości tygodniowej, a nie od jednego "morderczego" treningu. Lepiej zrobić 10 solidnych serii rozłożonych na 2 sesje niż 15 serii w jednej i nie dać rady przez 5 dni.', sourceLabel:'Mike Israetel / Volume Landmarks', level:'intermediate', goal:['muscle_gain'], tags:['volume','frequency','hypertrophy'] },
{ id:'training_005', category:'training', title:'Technika chroni i zwiększa stimulus', content:'Dobra technika to nie tylko bezpieczeństwo, to też lepsza aktywacja mięśnia docelowego. Skrócony zakres ruchu albo użycie rozmachu może odciążyć właśnie ten mięsień, który chcesz rozwinąć.', sourceLabel:'Brad Schoenfeld / Hypertrophy Research', level:'beginner', goal:['muscle_gain'], tags:['technique','range_of_motion','safety'] },
{ id:'training_006', category:'training', title:'Deload to część planu, nie porażka', content:'Deload to celowe zmniejszenie objętości lub intensywności po kilku tygodniach twardego treningu. Pozwala na regenerację i supercompensację. Pomijanie deloadów to szybka droga do stagnacji lub przetrenowania.', sourceLabel:'Mike Israetel / Periodization', level:'intermediate', goal:['muscle_gain','strength'], tags:['deload','recovery','periodization'] },
{ id:'training_007', category:'training', title:'Stretch position to premium stimulus', content:'Ćwiczenia z maksymalnym rozciągnięciem mięśnia pod obciążeniem (np. Incline Curl, Cable Fly, RDL) dają silniejszy sygnał do wzrostu niż ćwiczenia bez rozciągnięcia. To jeden z kluczowych wniosków najnowszych badań.', sourceLabel:'Brad Schoenfeld / Muscle Length Research', level:'advanced', goal:['muscle_gain'], tags:['stretch_position','hypertrophy','exercise_selection'] },
{ id:'training_008', category:'training', title:'Konsekwencja bije intensywność', content:'Jeden ekstremalny trening nie zastąpi regularnych, średnio intensywnych sesji. Najlepszy program to ten, którego faktycznie przestrzegasz przez miesiące. Regularność jest ważniejsza niż perfekcja.', sourceLabel:'Eric Helms / Training Principles', level:'beginner', goal:['muscle_gain','fat_loss','health'], tags:['consistency','adherence','long_term'] },
{ id:'training_009', category:'training', title:'Tempo powtórzeń — faza ekscentryczna', content:'Faza ekscentryczna (opuszczanie ciężaru) generuje silny sygnał hipertroficzny. Kontrolowane opuszczanie (2–3 sekundy) może zwiększyć stimulus bez dodawania dodatkowych serii.', sourceLabel:'Brad Schoenfeld / Tempo Research', level:'intermediate', goal:['muscle_gain'], tags:['eccentric','tempo','hypertrophy'] },
{ id:'training_010', category:'training', title:'Przerwy między seriami mają znaczenie', content:'Przerwy 2–3 minuty między seriami pozwalają na pełniejszą regenerację fosfokreatyny i lepszą jakość kolejnej serii. Krótsze przerwy mogą zwiększać "pompę", ale kosztem jakości wykonania.', sourceLabel:'Brad Schoenfeld / Rest Intervals', level:'intermediate', goal:['muscle_gain','strength'], tags:['rest_periods','strength','hypertrophy'] },
{ id:'training_011', category:'training', title:'Ból to nie to samo co zmęczenie', content:'Uczucie "pieczenia" mięśnia podczas treningu to norma. Ostry ból w stawie lub ścięgnie to sygnał stop. Ignorowanie bólu stawów lub więzadeł to najszybsza droga do przerwy przymusowej, nie planowanej.', sourceLabel:'Sports Medicine Practice', level:'beginner', goal:['health','muscle_gain'], tags:['pain','injury','awareness'] },
{ id:'training_012', category:'training', title:'Każda partia potrzebuje MV', content:'Minimum volume (MV) to minimalna liczba serii tygodniowo, która utrzymuje masę mięśniową. Nawet w fazach redukcji lub przy ograniczonym czasie warto utrzymać przynajmniej MV dla każdej partii.', sourceLabel:'Mike Israetel / Volume Landmarks', level:'advanced', goal:['muscle_gain','fat_loss'], tags:['minimum_volume','maintenance','periodization'] },
{ id:'training_013', category:'training', title:'Trening siłowy w redukcji — tak', content:'Trening siłowy w redukcji kalorycznej chroni masę mięśniową i utrzymuje siłę. Bez niego większy procent tracona masy to mięśnie, a nie tłuszcz. Nie odpuszczaj treningu siłowego w redukcji.', sourceLabel:'Eric Helms / Body Recomposition', level:'beginner', goal:['fat_loss','recomp'], tags:['strength_training','fat_loss','muscle_preservation'] },
{ id:'training_014', category:'training', title:'Częstotliwość dla początkujących', content:'Osoby początkujące adaptują się szybciej przy wyższej częstotliwości trenowania danej partii. 2–3 razy w tygodniu na każdą grupę mięśniową daje lepsze efekty niż trening każdej partii raz na 7 dni.', sourceLabel:'Mike Israetel / Beginner Training', level:'beginner', goal:['muscle_gain'], tags:['frequency','beginner','adaptation'] },
{ id:'training_015', category:'training', title:'SFR — wybieraj mądrze', content:'Stimulus to Fatigue Ratio (SFR) to stosunek korzyści treningowych do zmęczenia. Deadlift ma niski SFR (dużo zmęczenia ogólnego), Cable Fly ma wysoki (dużo stimulus klatki, mało zmęczenia). Wybieraj ćwiczenia z wysokim SFR dla każdej partii.', sourceLabel:'Mike Israetel / Exercise Selection', level:'advanced', goal:['muscle_gain'], tags:['sfr','exercise_selection','fatigue'] },
{ id:'training_016', category:'training', title:'Cardio nie zjada mięśni', content:'Umiarkowane cardio nie niszczy masy mięśniowej, jeśli podaż białka i kalorii jest odpowiednia. Problem pojawia się przy ekstremalnym cardio w połączeniu z dużym deficytem i małym białkiem.', sourceLabel:'Eric Helms / Cardio & Muscle', level:'intermediate', goal:['fat_loss','health'], tags:['cardio','muscle_loss','myths'] },
{ id:'training_017', category:'training', title:'Trening to stres — recovery jest odpowiedzią', content:'Trening to celowo zadany stres. Adaptacja (wzrost mięśni, siły) następuje w czasie odpoczynku, nie podczas sesji. Bez odpowiedniego snu, jedzenia i czasu na regenerację, trening daje gorsze efekty.', sourceLabel:'Mike Israetel / Supercompensation', level:'beginner', goal:['muscle_gain','health'], tags:['recovery','supercompensation','adaptation'] },
{ id:'training_018', category:'training', title:'Kompetencja techniczna to fundament', content:'Zanim dodasz objętość lub ciężar, upewnij się, że masz solidną technikę. Dobre wzorce ruchowe skumulowane przez lata to najlepsza ochrona przed kontuzjami i gwarancja długoterminowego progresu.', sourceLabel:'Sports Science Practice', level:'beginner', goal:['muscle_gain','health'], tags:['technique','movement_patterns','long_term'] },
{ id:'training_019', category:'training', title:'Izolacje mają sens', content:'Ćwiczenia izolowane (np. curl, leg extension, lateral raise) mają ważne miejsce w programie hipertroficznym. Pozwalają na precyzyjny targeting słabszych partii bez obciążania reszty ciała.', sourceLabel:'Brad Schoenfeld / Isolation Exercises', level:'intermediate', goal:['muscle_gain'], tags:['isolation','targeting','hypertrophy'] },
{ id:'training_020', category:'training', title:'Log to Twój najlepszy trener', content:'Zapisywanie ciężarów, powtórzeń i RIR pozwala śledzić progres i podejmować lepsze decyzje. Trening "na pamięć" prowadzi do stagnacji, bo mózg lubi komfort, nie progresję.', sourceLabel:'Eric Helms / Training Log', level:'beginner', goal:['muscle_gain','strength'], tags:['logging','tracking','progressive_overload'] },

// ─── REGENERACJA (12) ──────────────────────────────────────────────────────
{ id:'recovery_001', category:'recovery', title:'DOMS nie oznacza lepszego treningu', content:'Bolesność mięśniowa po treningu (DOMS) może się pojawić, ale nie jest głównym wskaźnikiem skuteczności. Lepszym sygnałem jest długoterminowy progres, jakość techniki i dobra regeneracja między jednostkami.', sourceLabel:'Brad Schoenfeld / Hypertrophy Research', level:'beginner', goal:['muscle_gain','recomp'], tags:['doms','recovery','hypertrophy'] },
{ id:'recovery_002', category:'recovery', title:'Aktywny odpoczynek przyspiesza regenerację', content:'Lekki spacer, rozciąganie lub pływanie w dni wolne od treningu mogą przyspieszyć usuwanie metabolitów i zmniejszyć zakwasy. Totalny bezruch nie zawsze jest najlepszą strategią regeneracyjną.', sourceLabel:'Sports Science Practice', level:'beginner', goal:['muscle_gain','health'], tags:['active_recovery','rest_day','movement'] },
{ id:'recovery_003', category:'recovery', title:'Białko po treningu — okno jest szersze niż myślisz', content:'"Okno anaboliczne" nie zamyka się po 30 minutach od treningu. Badania sugerują, że porcja białka w ciągu 1–2 godzin po treningu wystarczy. Nie musisz biec z shakerem przez siłownię.', sourceLabel:'Alan Aragon / Nutrient Timing', level:'intermediate', goal:['muscle_gain'], tags:['protein','post_workout','timing'] },
{ id:'recovery_004', category:'recovery', title:'Kreatyna wspiera regenerację', content:'Kreatyna pomaga w resyntezie ATP podczas intensywnych serii, ale ma też potencjalnie pozytywny wpływ na regenerację mięśniową. To jeden z najlepiej przebadanych suplementów z realną wartością.', sourceLabel:'ISSN / Creatine Position Stand', level:'intermediate', goal:['muscle_gain','strength'], tags:['creatine','atp','recovery'] },
{ id:'recovery_005', category:'recovery', title:'Zimna kąpiel — nie zawsze pomaga', content:'Zimna woda po treningu może redukować stan zapalny i bolesność, ale może też hamować adaptacje hipertroficzne, bo stan zapalny jest częścią sygnału do wzrostu. Stosuj z rozsądkiem, szczególnie nie po każdym treningu.', sourceLabel:'Sports Science Research', level:'advanced', goal:['muscle_gain','recovery'], tags:['cold_water','inflammation','adaptation'] },
{ id:'recovery_006', category:'recovery', title:'Mobilność to długoterminowa inwestycja', content:'Regularna praca nad zakresem ruchu chroni stawy, zmniejsza ryzyko kontuzji i pozwala na pełniejsze wykonanie ćwiczeń. 10 minut dziennie przez kilka tygodnie robi realną różnicę.', sourceLabel:'Sports Medicine Practice', level:'beginner', goal:['health','muscle_gain'], tags:['mobility','flexibility','injury_prevention'] },
{ id:'recovery_007', category:'recovery', title:'Kortyzol a regeneracja', content:'Kortyzol to naturalny hormon stresu, który pomaga przy treningu, ale chroniczne jego podniesienie (praca, brak snu, diety) spowalnia regenerację. Stres całkościowy (treningowy + życiowy) wpływa na zdolność do adaptacji.', sourceLabel:'Peter Attia / Stress Hormones', level:'intermediate', goal:['health','muscle_gain'], tags:['cortisol','stress','hormones'] },
{ id:'recovery_008', category:'recovery', title:'Masa ciała a regeneracja', content:'Podczas snu organizm intensywnie odbudowuje tkanki. Niedobór kalorii, szczególnie białka, może hamować te procesy. Zbyt agresywna redukcja może spowolnić regenerację po treningu.', sourceLabel:'Eric Helms / Recovery & Nutrition', level:'intermediate', goal:['fat_loss','muscle_gain'], tags:['calories','protein','night_recovery'] },
{ id:'recovery_009', category:'recovery', title:'Masaż i rollery — realne, ale nie magiczne', content:'Automasaż rollerem może zmniejszyć subiektywne uczucie bolesności i poprawić zakres ruchu tymczasowo. Nie "przywraca mięśni do zdrowia" ani nie usuwa kwasu mlekowego (który zresztą znika szybko po treningu).', sourceLabel:'Sports Science Research', level:'beginner', goal:['health','recovery'], tags:['foam_rolling','massage','myths'] },
{ id:'recovery_010', category:'recovery', title:'Odpoczynek między sesjami ma matematykę', content:'Mała partia (biceps, łydki) regeneruje się w 24–48 godzin. Duże partie (plecy, nogi) mogą potrzebować 48–72 godzin. Zbyt częste trenowanie tej samej partii zanim wróci do pełni może hamować efekty.', sourceLabel:'Mike Israetel / Recovery Times', level:'intermediate', goal:['muscle_gain'], tags:['recovery_time','frequency','planning'] },
{ id:'recovery_011', category:'recovery', title:'Witamina D i regeneracja', content:'Witamina D uczestniczy w funkcji mięśniowej i regulacji stanu zapalnego. Niedobór jest powszechny, szczególnie w Polsce w miesiącach bez słońca. Suplementacja 2000–4000 IU dziennie to zazwyczaj bezpieczna strategia.', sourceLabel:'Examine.com / Vitamin D', level:'intermediate', goal:['health','muscle_gain'], tags:['vitamin_d','inflammation','immunity'] },
{ id:'recovery_012', category:'recovery', title:'Alkohol a regeneracja mięśniowa', content:'Alkohol hamuje syntezę białek mięśniowych i zaburza sen regeneracyjny. Nie musisz całkowicie rezygnować, ale sesja po treningu to najgorszy moment, jeśli zależy Ci na efektach.', sourceLabel:'Sports Science Research', level:'intermediate', goal:['muscle_gain','health'], tags:['alcohol','mps','recovery'] },

// ─── STRES (10) ────────────────────────────────────────────────────────────
{ id:'stress_001', category:'stress', title:'Stres potrafi zamaskować progres', content:'Wysoki stres może zwiększać retencję wody i pogarszać sen, przez co masa ciała chwilowo stoi mimo dobrego planu. Dlatego system patrzy na trend i zachowania, nie tylko na jedną liczbę.', sourceLabel:'Peter Attia / Stress & Health', level:'intermediate', goal:['fat_loss','health'], tags:['stress','water_retention','weight'] },
{ id:'stress_002', category:'stress', title:'Kortyzol i apetyt to tandem', content:'Chroniczny stres podnosi kortyzol, który zwiększa łaknienie, szczególnie na wysokoenergetyczne jedzenie. To ewolucyjna reakcja, a nie słabość charakteru. Zarządzanie stresem jest częścią zarządzania dietą.', sourceLabel:'Peter Attia / Cortisol Research', level:'intermediate', goal:['fat_loss','health'], tags:['cortisol','hunger','stress'] },
{ id:'stress_003', category:'stress', title:'Oddech jako narzędzie', content:'Powolny wydech (dłuższy niż wdech) aktywuje układ przywspółczulny i może szybko obniżyć pobudzenie stresowe. Technika 4-7-8 (wdech 4s, zatrzymanie 7s, wydech 8s) to prosta interwencja z realnym efektem.', sourceLabel:'Huberman Lab / Breathing Techniques', level:'beginner', goal:['health'], tags:['breathing','stress_reduction','nervous_system'] },
{ id:'stress_004', category:'stress', title:'Trening redukuje stres — do pewnej granicy', content:'Ćwiczenia fizyczne są świetnym reduktorem stresu. Ale przy już wysokim stresie życiowym, dodanie bardzo intensywnego treningu może go skumulować. Lekkość i regularność czasem bije intensywność.', sourceLabel:'Sports Science Practice', level:'intermediate', goal:['health','fat_loss'], tags:['exercise','stress_relief','intensity'] },
{ id:'stress_005', category:'stress', title:'Social media a stres podkorowy', content:'Ciągłe scrollowanie aktywuje układ nagrody i może paradoksalnie zwiększać poziom niepokoju. Wieczorne ograniczenie czasu przy ekranie to nie luddyzm, to strategia zdrowotna z coraz lepszym wsparciem badawczym.', sourceLabel:'General Wellness Research', level:'beginner', goal:['health'], tags:['social_media','sleep','stress'] },
{ id:'stress_006', category:'stress', title:'Stres a kompozycja ciała', content:'Osoby w chronicznym stresie mają tendencję do gromadzenia tkanki tłuszczowej szczególnie w okolicach brzucha, związaną z działaniem kortyzolu. Redukcja stresu jest więc częścią planu na sylwetkę.', sourceLabel:'Peter Attia / Metabolic Health', level:'intermediate', goal:['fat_loss','health'], tags:['cortisol','belly_fat','stress'] },
{ id:'stress_007', category:'stress', title:'Czas na naturze działa', content:'Przebywanie w naturze, nawet krótki spacer w parku, może obniżać markerem stresu i poprawiać nastrój. Nie jest to magia, ale regularna ekspozycja na środowisko naturalne ma realne korzyści fizjologiczne.', sourceLabel:'General Wellness Research', level:'beginner', goal:['health'], tags:['nature','stress_relief','mental_health'] },
{ id:'stress_008', category:'stress', title:'Relacje społeczne to zdrowie', content:'Izolacja społeczna jest jednym z silnych predyktorów złego zdrowia i krótszego życia. Regularne kontakty społeczne, nawet krótkie, mają mierzalny efekt na biomarkery stresu i stan zapalny.', sourceLabel:'Peter Attia / Longevity Research', level:'beginner', goal:['health'], tags:['social','connection','longevity'] },
{ id:'stress_009', category:'stress', title:'Perfekcjonizm a zdrowie', content:'Dążenie do perfekcji w diecie i treningu może być źródłem chronicznego stresu. Filozofia "wystarczająco dobre" często prowadzi do lepszych długoterminowych wyników niż obsesja na punkcie idealnego wykonania.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['health','fat_loss'], tags:['perfectionism','adherence','mental_health'] },
{ id:'stress_010', category:'stress', title:'Stres a trawienie', content:'Układ nerwowy reguluje też trawienie. W stanach wysokiego stresu trawienie może być zaburzone, co prowadzi do wzdęć, dyskomfortu i gorszego wchłaniania. To kolejny powód, dla którego zarządzanie stresem jest częścią zdrowia żywieniowego.', sourceLabel:'General Health Research', level:'intermediate', goal:['health'], tags:['digestion','gut','stress'] },

// ─── SUPLEMENTY (10) ───────────────────────────────────────────────────────
{ id:'supplement_001', category:'supplements', title:'Kreatyna działa przez regularność', content:'Kreatyna nie musi być brana idealnie przed treningiem. Najważniejsze jest regularne przyjmowanie — zazwyczaj 3–5 g dziennie — żeby utrzymać wysycenie mięśni. Pora dnia ma drugorzędne znaczenie.', sourceLabel:'ISSN / Creatine Position Stand', level:'beginner', goal:['muscle_gain','strength'], tags:['creatine','strength','supplements'] },
{ id:'supplement_002', category:'supplements', title:'Suplementy nie naprawią chaosu', content:'Kreatyna, witamina D czy omega-3 mogą być pomocne, ale nie zastąpią snu, odpowiedniej ilości kalorii, białka i regularnego treningu. Najpierw fundamenty, potem ewentualne dodatki.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['health','fat_loss','muscle_gain'], tags:['supplements','basics','habits'] },
{ id:'supplement_003', category:'supplements', title:'Witamina D to priorytet w Polsce', content:'W szerokości geograficznej Polski synteza witaminy D przez skórę jest efektywna tylko przez kilka miesięcy. Suplementacja 2000–4000 IU dziennie przez jesień i zimę jest rekomendowana przez większość towarzystw naukowych.', sourceLabel:'PTMR / Vitamin D Guidelines', level:'beginner', goal:['health'], tags:['vitamin_d','poland','immunity'] },
{ id:'supplement_004', category:'supplements', title:'Kofeina — najpopularniejszy ergogen', content:'Kofeina ma silne wsparcie naukowe jako wspomagacz treningu. 3–6 mg/kg masy ciała 30–60 minut przed treningiem może poprawić siłę, wytrzymałość i skupienie. Tolerancja rośnie, więc warto robić przerwy.', sourceLabel:'ISSN / Caffeine Position Stand', level:'intermediate', goal:['muscle_gain','fat_loss'], tags:['caffeine','ergogenic','performance'] },
{ id:'supplement_005', category:'supplements', title:'Odżywka białkowa to żywność, nie chemia', content:'WPC i WPI to przetworzony nabiał — skoncentrowane białko z mleka. To wygodny i tani sposób na uzupełnienie białka w diecie. Nie ma podstaw do traktowania ich jako "chemii" jeśli ogólna dieta jest zbilansowana.', sourceLabel:'General Nutrition Evidence', level:'beginner', goal:['muscle_gain','fat_loss'], tags:['whey','protein_powder','myths'] },
{ id:'supplement_006', category:'supplements', title:'Magnez — form ma znaczenie', content:'Nie wszystkie formy magnezu są równe. Magnez tlenek ma niskie wchłanianie. Glicynian i taurat wchłaniają się lepiej i są łagodniejsze dla układu pokarmowego. Dobre formy to zazwyczaj droższe produkty.', sourceLabel:'Examine.com / Magnesium Forms', level:'intermediate', goal:['health','sleep'], tags:['magnesium','forms','absorption'] },
{ id:'supplement_007', category:'supplements', title:'Beta-alanina i mrowienie', content:'Beta-alanina może poprawiać wytrzymałość mięśniową w seriach 8–15 powtórzeń. Charakterystyczne mrowienie (parestezja) po zażyciu to normalna reakcja, nie objaw szkodliwości. Efekty widoczne po kilku tygodniach regularnego stosowania.', sourceLabel:'ISSN / Beta-Alanine Review', level:'advanced', goal:['muscle_gain','strength'], tags:['beta_alanine','endurance','supplements'] },
{ id:'supplement_008', category:'supplements', title:'Cynk i testosteron', content:'Cynk jest niezbędny do produkcji testosteronu i funkcji immunologicznej. Niedobór cynku (częsty przy intensywnym treningu) może wpływać na hormony i regenerację. Mięso, pestki dyni i orzechy to naturalne źródła.', sourceLabel:'Examine.com / Zinc', level:'intermediate', goal:['muscle_gain','health'], tags:['zinc','testosterone','minerals'] },
{ id:'supplement_009', category:'supplements', title:'Ashwagandha na stres i testosteron', content:'Ashwagandha ma rosnące wsparcie badawcze dla redukcji kortyzolu, poprawy jakości snu i potencjalnie poziomu testosteronu. To jeden z niewielu adaptogenów z realną dokumentacją naukową.', sourceLabel:'Examine.com / Ashwagandha', level:'intermediate', goal:['health','muscle_gain','stress'], tags:['ashwagandha','cortisol','adaptogen'] },
{ id:'supplement_010', category:'supplements', title:'Najdroższy suplement to konsekwencja', content:'Żaden suplement nie zastąpi regularności. Osoba trenująca 3 razy w tygodniu przez rok bez suplementów osiągnie więcej niż osoba biorąca wszystko co możliwe, ale trenująca nieregularnie. Konsekwencja jest king.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['muscle_gain','fat_loss','health'], tags:['consistency','supplements','perspective'] },

// ─── WELL-BEING & NEAT (12) ────────────────────────────────────────────────
{ id:'wellbeing_001', category:'wellbeing', title:'Kroki to cichy spalacz kalorii', content:'NEAT — codzienna aktywność poza treningiem — potrafi mocno wpływać na wydatek energetyczny. Regularne kroki są często łatwiejsze do utrzymania niż dodatkowe sesje cardio i mogą mieć większy łączny efekt.', sourceLabel:'Lyle McDonald / Energy Balance', level:'beginner', goal:['fat_loss','health'], tags:['steps','neat','fat_loss'] },
{ id:'wellbeing_002', category:'wellbeing', title:'Siedzący tryb życia a metabolizm', content:'Długie siedzenie (nawet przy regularnym treningu) wiąże się z gorszymi markerami metabolicznymi. Przerwy co 30–60 minut — krótki spacer, wstanie, kilka kroków — mogą łagodzić negatywne efekty pracy biurowej.', sourceLabel:'General Health Research', level:'beginner', goal:['health'], tags:['sedentary','neat','metabolic_health'] },
{ id:'wellbeing_003', category:'wellbeing', title:'Światło słoneczne rano', content:'Ekspozycja na naturalne światło w ciągu pierwszej godziny po przebudzeniu synchronizuje zegar biologiczny, poprawia nastrój i wspiera regularność snu. Nawet przez okno (choć mniej efektywnie) lub krótkie wyjście na zewnątrz.', sourceLabel:'Huberman Lab / Light & Circadian Rhythm', level:'beginner', goal:['health','sleep'], tags:['sunlight','circadian','mood'] },
{ id:'wellbeing_004', category:'wellbeing', title:'Chodzenie to niedoceniane narzędzie', content:'Regularne spacery obniżają poziom glukozy po posiłkach, wspierają zdrowie sercowo-naczyniowe, poprawiają nastrój i redukują stres. To jedno z najlepiej przebadanych i najtańszych narzędzi zdrowotnych.', sourceLabel:'Peter Attia / Exercise Is Medicine', level:'beginner', goal:['health','fat_loss'], tags:['walking','glucose','cardiovascular'] },
{ id:'wellbeing_005', category:'wellbeing', title:'Spacer po posiłku to nie mit', content:'10–15 minutowy spacer po posiłku (szczególnie wysokowęglowodanowym) może znacznie obniżyć odpowiedź glikemiczną. To prosta i efektywna strategia dla osób dbających o insulinowrażliwość.', sourceLabel:'General Health Research', level:'beginner', goal:['health'], tags:['post_meal_walk','glucose','insulin'] },
{ id:'wellbeing_006', category:'wellbeing', title:'Zdrowie to nie tylko sylwetka', content:'Zdrowie to kompozycja siły, wytrzymałości, elastyczności, snu, zdrowia psychicznego i relacji społecznych. Obsesja na punkcie wagi lub masy mięśniowej może paradoksalnie obniżać ogólną jakość życia.', sourceLabel:'Peter Attia / Longevity Principles', level:'beginner', goal:['health'], tags:['holistic_health','mental_health','perspective'] },
{ id:'wellbeing_007', category:'wellbeing', title:'Natura i stres — badania mówią tak', content:'Przebywanie w środowisku naturalnym (lasy, parki, woda) ma mierzalny wpływ na redukcję kortyzolu i poprawę nastroju. Nawet krótki kontakt z naturą kilka razy w tygodniu przynosi korzyści.', sourceLabel:'Environmental Health Research', level:'beginner', goal:['health'], tags:['nature','cortisol','mental_health'] },
{ id:'wellbeing_008', category:'wellbeing', title:'Więzi społeczne są ważniejsze niż myślisz', content:'Badania nad długowiecznością (Blue Zones) wskazują, że silne więzi społeczne są jednym z kluczowych czynników. Samotność ma fizjologiczny wpływ na zdrowie porównywalny do palenia papierosów.', sourceLabel:'Peter Attia / Longevity Research', level:'beginner', goal:['health'], tags:['social','longevity','connection'] },
{ id:'wellbeing_009', category:'wellbeing', title:'Małe nawyki > wielkie rewolucje', content:'Zmiana jednej małej rzeczy i utrzymanie jej przez miesiąc jest skuteczniejsza niż radykalna zmiana wszystkiego jednocześnie. Mały, stabilny progres w zdrowych nawykach kumuluje się w imponujące wyniki po roku.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['health','fat_loss','muscle_gain'], tags:['habits','small_changes','consistency'] },
{ id:'wellbeing_010', category:'wellbeing', title:'Praca stojąca — nie tylko moda', content:'Naprzemienne siedzenie i stanie podczas pracy poprawia wydatek energetyczny (NEAT) i zmniejsza negatywne efekty długiego siedzenia. Biurko regulowane to inwestycja w zdrowie, nie gadżet.', sourceLabel:'General Health Research', level:'beginner', goal:['health','fat_loss'], tags:['standing_desk','neat','office'] },
{ id:'wellbeing_011', category:'wellbeing', title:'Zdrowie metaboliczne zaczyna się od snu', content:'Niedobór snu zaburza gospodarkę glukozową, insulinowrażliwość i profil hormonalny. Osoby śpiące regularnie 7–9 godzin mają lepsze parametry metaboliczne niezależnie od diety i treningu.', sourceLabel:'Matthew Walker / Sleep & Metabolism', level:'intermediate', goal:['health','fat_loss'], tags:['metabolic_health','insulin','sleep'] },
{ id:'wellbeing_012', category:'wellbeing', title:'Cel poza sylwetką daje wytrwałość', content:'Osoby ćwiczące dla zdrowia, siły lub dobrego samopoczucia zwykle ćwiczą dłużej niż te motywowane wyłącznie wyglądem. Znajdź swoje głębsze "po co" — to naturalny bufor w trudnych tygodniach.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['health','fat_loss','muscle_gain'], tags:['motivation','purpose','long_term'] },

// ─── ADHERENCE / MINDSET (15) ──────────────────────────────────────────────
{ id:'adherence_001', category:'adherence', title:'Nie ukrywaj gorszego dnia', content:'Gorszy dzień nie niszczy procesu, ale brak danych utrudnia reakcję trenera. Wpisz prawdę, nawet jeśli nie było idealnie — system ma pomagać w realnym życiu, a nie tylko rejestrować sukcesy.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['fat_loss','muscle_gain','health'], tags:['honesty','check_in','coaching'] },
{ id:'adherence_002', category:'adherence', title:'Najważniejszy jest powrót do planu', content:'Każdy ma gorszy tydzień. Kluczem nie jest perfekcja, ale szybkość powrotu do planu po potknięciu. Osoby, które wracają szybko, osiągają więcej niż te, które próbują być idealne.', sourceLabel:'Lyle McDonald / Flexible Dieting', level:'beginner', goal:['fat_loss','health','muscle_gain'], tags:['bounce_back','consistency','mindset'] },
{ id:'adherence_003', category:'adherence', title:'80% to wystarczające', content:'80% przestrzegania planu przez długi czas daje lepsze efekty niż 100% przez 3 tygodnie i kapitulacja. Dobry plan to taki, który możesz realizować przez miesiące, nie przez kilka tygodni na sile woli.', sourceLabel:'Alan Aragon / Flexible Dieting', level:'beginner', goal:['fat_loss','health','muscle_gain'], tags:['adherence','sustainability','80_percent'] },
{ id:'adherence_004', category:'adherence', title:'Myślenie zero-jedynkowe niszczy rezultaty', content:'"Zjadłem za dużo, więc wszystko stracone" to pułapka. Jedna kolacja nie niszczy tygodnia. Jeden tydzień nie niszczy miesiąca. Procesowe myślenie o długim trendzie jest ważniejsze niż ocenianie każdego dnia.', sourceLabel:'Lyle McDonald / Mental Approach', level:'beginner', goal:['fat_loss','health'], tags:['all_or_nothing','mindset','flexibility'] },
{ id:'adherence_005', category:'adherence', title:'Motywacja przemija, system zostaje', content:'Motywacja jest niestabilna i zależy od nastroju, snu i okoliczności. System (stałe godziny treningu, zaplanowane posiłki, logowanie) działa niezależnie od nastroju. Buduj system, nie poluj na motywację.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['muscle_gain','fat_loss','health'], tags:['motivation','system','habits'] },
{ id:'adherence_006', category:'adherence', title:'Porównuj siebie do siebie', content:'Porównywanie się z innymi w siłowni lub social media rzadko daje inspirację, częściej frustrację. Jedyną osobą, z którą warto się porównywać, jest ty sprzed miesiąca. Osobisty progres to właściwa metryka.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['health','muscle_gain','fat_loss'], tags:['comparison','progress','mindset'] },
{ id:'adherence_007', category:'adherence', title:'Efekty są opóźnione', content:'Zmiany ciała wymagają czasu. Często widzisz efekty w danych (waga, siła) zanim widać je wyraźnie w lustrze. Ufaj procesowi i danym, a nie chwilowym odczuciom przy patrzeniu w lustro.', sourceLabel:'Lyle McDonald / Body Composition', level:'beginner', goal:['fat_loss','muscle_gain'], tags:['patience','results','time'] },
{ id:'adherence_008', category:'adherence', title:'Środowisko decyduje o wyborach', content:'Masz mniej woli niż myślisz — Twoje środowisko decyduje o wyborach bardziej niż charakter. Zdrowe jedzenie w zasięgu wzroku, wypakowana torba treningowa, stała godzina treningu — to inżynieria adherence.', sourceLabel:'General Behavioural Science', level:'intermediate', goal:['health','fat_loss','muscle_gain'], tags:['environment','willpower','habits'] },
{ id:'adherence_009', category:'adherence', title:'Świętowanie małych wygranych', content:'Doceniaj małe postępy — pierwszy trening po przerwie, tydzień bez pominięcia posiłków, nowy rekord w ćwiczeniu. Mózg uczy się przez nagrody. Ignorowanie małych wygranych odbiera paliwo do kontynuacji.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['health','muscle_gain','fat_loss'], tags:['small_wins','motivation','celebration'] },
{ id:'adherence_010', category:'adherence', title:'Nieplanowane jedzenie to nie grzech', content:'Urodziny, wesela, spotkania ze znajomymi — życie ma swoje momenty. Planowanie przestrzeni na elastyczność jest strategią, nie słabością. System żywieniowy ma pasować do życia, nie odwrotnie.', sourceLabel:'Alan Aragon / Flexible Dieting', level:'beginner', goal:['fat_loss','health'], tags:['social_eating','flexibility','life_balance'] },
{ id:'adherence_011', category:'adherence', title:'Dlaczego ważniejsze niż jak', content:'Znalezienie osobistego powodu zmiany (zdrowie dla dzieci, energia do pracy, pewność siebie) daje wytrwałość przy trudnościach. Sam plan treningowy bez głębokiej motywacji wystarczy na pierwsze tygodnie.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['health','fat_loss','muscle_gain'], tags:['why','motivation','purpose'] },
{ id:'adherence_012', category:'adherence', title:'Raportowanie to część procesu', content:'Regularne check-iny nie są formalnością — to dane, które pozwalają dostosować plan do realu. Klient, który raportuje regularnie (nawet słabe tygodnie), robi zazwyczaj szybszy progres niż ten, który znika gdy jest ciężko.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['fat_loss','muscle_gain','health'], tags:['reporting','check_in','data'] },
{ id:'adherence_013', category:'adherence', title:'Odpuść sobie perfekcjonizm w żywieniu', content:'Ortoreksja (obsesja na punkcie "czystego" jedzenia) jest realnym problemem. Dobra dieta to nie eliminacja wszystkiego co "nieczyste", ale rozsądna, zrównoważona i możliwa do utrzymania całość.', sourceLabel:'Areté Coaching Practice', level:'intermediate', goal:['health'], tags:['orthorexia','balance','mental_health'] },
{ id:'adherence_014', category:'adherence', title:'Cierpliwość to supermoc', content:'Prawdziwe zmiany ciała (utrata tłuszczu, budowa mięśni, poprawa siły) wymagają miesięcy i lat. Oczekiwanie efektów po 4 tygodniach jest jak ocenianie filmu po pierwszych 5 minutach. Daj procesowi czas.', sourceLabel:'Mike Israetel / Long Term Thinking', level:'beginner', goal:['fat_loss','muscle_gain','health'], tags:['patience','long_term','realistic_expectations'] },
{ id:'adherence_015', category:'adherence', title:'Trener widzi to czego nie widzisz', content:'Z zewnątrz często widać rzeczy, które trudno dostrzec z środka — wzorce, tendencje, sabotujące zachowania. Dlatego warto być otwartym na feedback, nawet gdy wydaje się niewygodny.', sourceLabel:'Areté Coaching Practice', level:'beginner', goal:['fat_loss','muscle_gain','health'], tags:['coaching','feedback','perspective'] },

]

// ─── FUNKCJE ───────────────────────────────────────────────────────────────

function hashString(str) {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i)
    hash |= 0
  }
  return Math.abs(hash)
}

function getDateKey(date = new Date()) {
  return date.toISOString().slice(0, 10)
}

export function getDailyTip(date = new Date()) {
  const dateKey = getDateKey(date)
  const index = hashString(dateKey) % DAILY_TIPS.length
  return DAILY_TIPS[index]
}

export function getDailyTipForUser(userId, date = new Date()) {
  const dateKey = getDateKey(date)
  const index = hashString(`${userId}-${dateKey}`) % DAILY_TIPS.length
  return DAILY_TIPS[index]
}

export function getTipsByCategory(category) {
  return DAILY_TIPS.filter(t => t.category === category)
}

export function getTipsByGoal(goal) {
  return DAILY_TIPS.filter(t => t.goal.includes(goal))
}
